#!/usr/bin/env python3
"""
Disk Loader RTL Generator
Generates a Verilog 2005 structural module that initialises a disk memory
array with random data at simulation startup.

Config JSON fields:
    diskMemPath      - Verilog instance identifier for the disk array
                       e.g. "byte_t disk[DISK_SIZE];"  (used in comments /
                       the for-loop target name is parsed from this)
    metaDataFilePath - Path where meta.txt will be written
    diskSize         - Number of bytes in the disk (integer)
    startupDelay     - Delay ticks before initialisation begins (integer)
    Output_FilePath  - Destination path for the generated .v file
"""

import json
import os
import random
import sys
import re
from datetime import datetime, timezone

def _utcnow() -> str:
    """Return current UTC time as an ISO-8601 string (seconds precision)."""
    return datetime.now(timezone.utc).isoformat(timespec='seconds').replace('+00:00', 'Z')


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def parse_array_name(disk_mem_path: str) -> str:
    """
    Extract the bare array identifier from a C/Verilog-style declaration.
    e.g. 'byte_t disk[DISK_SIZE];' -> 'disk'
    Falls back to the raw string if no match is found.
    """
    match = re.search(r'\b(\w+)\s*\[', disk_mem_path)
    if match:
        return match.group(1)
    # Fallback: use the whole string stripped of whitespace
    return disk_mem_path.strip()


def module_name_from_path(output_file_path: str) -> str:
    """Return the base filename without extension, used as the module name."""
    base = os.path.basename(output_file_path)
    name, _ = os.path.splitext(base)
    return name


def ensure_dir(path: str):
    """Create parent directories for *path* if they do not exist."""
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)


# ---------------------------------------------------------------------------
# Verilog generation
# ---------------------------------------------------------------------------

def generate_verilog(module: str, array_name: str, disk_size: int,
                     startup_delay: int) -> str:
    """
    Build a Verilog 2005-compliant module string.

    The module contains a single 'initial' block that:
      1. Waits <startup_delay> time units.
      2. Uses a for-loop to assign a random hex byte to every element of the
         disk array.

    All random values are generated at Python runtime and hard-coded into the
    output so the simulation is fully deterministic and requires no $random.
    """

    # Pre-generate every random byte so the .v is self-contained.
    rand_bytes = [random.randint(0, 0xFF) for _ in range(disk_size)]

    assignments = "\n".join(
        f"        {array_name}[{i}] = 8'h{val:02X};"
        for i, val in enumerate(rand_bytes)
    )

    verilog = (
        f"// Auto-generated by gen_disk_loader.py\n"
        f"// Generated : {_utcnow()}\n"
        f"// Disk size : {disk_size} bytes\n"
        f"// Startup delay : {startup_delay}\n"
        f"// Verilog standard: IEEE 1364-2005\n"
        f"// Array target : {array_name} (declared in parent RTL project)\n"
        f"\n"
        f"module {module};\n"
        f"\n"
        f"    initial begin\n"
        f"        #{startup_delay};\n"
        f"{assignments}\n"
        f"    end\n"
        f"\n"
        f"endmodule\n"
    )

    return verilog, rand_bytes


# ---------------------------------------------------------------------------
# Metadata file
# ---------------------------------------------------------------------------

def write_metadata(meta_path: str, module: str, array_name: str,
                   disk_size: int, startup_delay: int,
                   output_path: str, rand_bytes: list):
    """Write a human-readable metadata summary to *meta_path*."""
    ensure_dir(meta_path)
    checksum = sum(rand_bytes) & 0xFFFFFFFF  # simple 32-bit additive checksum

    with open(meta_path, "w") as f:
        f.write("=== Disk Loader Generation Metadata ===\n")
        f.write(f"Generated     : {_utcnow()}\n")
        f.write(f"Module        : {module}\n")
        f.write(f"Array name    : {array_name}\n")
        f.write(f"Disk size     : {disk_size} bytes\n")
        f.write(f"Startup delay : {startup_delay}\n")
        f.write(f"Output file   : {output_path}\n")
        f.write(f"Checksum (add): 0x{checksum:08X}\n")
        f.write("\n=== Disk Contents ===\n")
        row_size = 16
        for row_idx in range(0, disk_size, row_size):
            chunk = rand_bytes[row_idx : row_idx + row_size]
            hex_str = " ".join(f"{b:02X}" for b in chunk)
            f.write(f"line {row_idx // row_size:>6} : {hex_str}\n")

    print(f"[meta] Written -> {meta_path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        print("Usage: gen_disk_loader.py <config.json>")
        sys.exit(1)

    config_path = sys.argv[1]
    with open(config_path, "r") as f:
        cfg = json.load(f)

    # --- Read config fields ------------------------------------------------
    disk_mem_path     = cfg["diskMemPath"]
    meta_data_path    = cfg["metaDataFilePath"]
    disk_size         = int(cfg["diskSize"])
    startup_delay     = int(cfg["startupDelay"])
    output_file_path  = cfg["Output_FilePath"]

    # --- Derive names ------------------------------------------------------
    array_name  = parse_array_name(disk_mem_path)
    module      = module_name_from_path(output_file_path)

    print(f"[config] Module name : {module}")
    print(f"[config] Array name  : {array_name}")
    print(f"[config] Disk size   : {disk_size} bytes")
    print(f"[config] Delay       : {startup_delay}")

    # --- Generate Verilog --------------------------------------------------
    verilog_src, rand_bytes = generate_verilog(
        module, array_name, disk_size, startup_delay
    )

    ensure_dir(output_file_path)
    with open(output_file_path, "w") as f:
        f.write(verilog_src)
    print(f"[rtl]  Written -> {output_file_path}")

    # --- Write metadata ----------------------------------------------------
    write_metadata(
        meta_data_path, module, array_name,
        disk_size, startup_delay, output_file_path, rand_bytes
    )

    print("[done] Generation complete.")


if __name__ == "__main__":
    main()
