module tb_fanout;

 Everywhere_TOP uut(
    .clk(clk_i),
    .rst(rst_i),
    .icache_icache_en_i(icache_icache_en_i_i),
    .icache_p_addr_i(icache_p_addr_i_i),                // p_address_t
    .icache_v_addr_i(icache_v_addr_i_i),                // v_address_t = address_t
    .icache_num_valid_IDM_slots_i(icache_num_valid_IDM_slots_i_i),   // [$clog2(NUM_IDM_SLOTS):0]
    .icache_hit_o(icache_hit_o_i),
    .icache_instruction_line_o(icache_instruction_line_o_i),    // 16-byte cache line, LSB-first
    .core_ld_addr_0_V_i(core_ld_addr_0_V_i_i),
    .core_ld_addr_0_i(core_ld_addr_0_i_i),
    .core_ld_addr_1_V_i(core_ld_addr_1_V_i_i),
    .core_ld_addr_1_i(core_ld_addr_1_i_i),
    .core_stq_full_0_i(core_stq_full_0_i_i),
    .core_stq_full_1_i(core_stq_full_1_i_i),
    .core_stq_full_2_i(core_stq_full_2_i_i),
    .core_stq_full_3_i(core_stq_full_3_i_i),
    .core_stq_empty_0_i(core_stq_empty_0_i_i),
    .core_stq_empty_1_i(core_stq_empty_1_i_i),
    .core_stq_empty_2_i(core_stq_empty_2_i_i),
    .core_stq_empty_3_i(core_stq_empty_3_i_i),
    .core_stq_addr_0_i(core_stq_addr_0_i_i),
    .core_stq_addr_1_i(core_stq_addr_1_i_i),
    .core_stq_addr_2_i(core_stq_addr_2_i_i),
    .core_stq_addr_3_i(core_stq_addr_3_i_i),
    .core_stq_bitvec_0_i(core_stq_bitvec_0_i_i),
    .core_stq_bitvec_1_i(core_stq_bitvec_1_i_i),
    .core_stq_bitvec_2_i(core_stq_bitvec_2_i_i),
    .core_stq_bitvec_3_i(core_stq_bitvec_3_i_i),
    .core_stq_data_0_i(core_stq_data_0_i_i),
    .core_stq_data_1_i(core_stq_data_1_i_i),
    .core_stq_data_2_i(core_stq_data_2_i_i),
    .core_stq_data_3_i(core_stq_data_3_i_i),
    .core_ld_addr_MIO_V_i(core_ld_addr_MIO_V_i_i),
    .core_ld_addr_MIO_i(core_ld_addr_MIO_i_i),
    .core_stq_info_mio_empty_i(core_stq_info_mio_empty_i_i),
    .core_stq_info_mio_addr_i(core_stq_info_mio_addr_i_i),
    .core_stq_info_mio_data_i(core_stq_info_mio_data_i_i),
    .core_memStage_CLR_REQ_0_i(core_memStage_CLR_REQ_0_i_i),
    .core_memStage_CLR_REQ_1_i(core_memStage_CLR_REQ_1_i_i),
    .core_memStage_CLR_REQ_2_i(core_memStage_CLR_REQ_2_i_i),
    .core_memStage_CLR_REQ_3_i(core_memStage_CLR_REQ_3_i_i),
    .core_memStage_CLR_REQ_MIO_i(core_memStage_CLR_REQ_MIO_i_i),
    .out2Core_reqServed_0_o(out2Core_reqServed_0_o_i),
    .out2Core_reqServed_1_o(out2Core_reqServed_1_o_i),
    .out2Core_hit_0_o(out2Core_hit_0_o_i),
    .out2Core_hit_1_o(out2Core_hit_1_o_i),
    .out2Core_hit_2_o(out2Core_hit_2_o_i),
    .out2Core_hit_3_o(out2Core_hit_3_o_i),
    .out2Core_cacheline_0_o(out2Core_cacheline_0_o_i),
    .out2Core_cacheline_1_o(out2Core_cacheline_1_o_i),
    .out2Core_cacheline_2_o(out2Core_cacheline_2_o_i),
    .out2Core_cacheline_3_o(out2Core_cacheline_3_o_i),
    .out2Core_writeSuccess_0_o(out2Core_writeSuccess_0_o_i),
    .out2Core_writeSuccess_1_o(out2Core_writeSuccess_1_o_i),
    .out2Core_writeSuccess_2_o(out2Core_writeSuccess_2_o_i),
    .out2Core_writeSuccess_3_o(out2Core_writeSuccess_3_o_i),
    .out2Core_writeSuccess_MIO_o(out2Core_writeSuccess_MIO_o_i),
    .out2Core_hit_MIO_o(out2Core_hit_MIO_o_i),
    .out2Core_reqServed_MIO_o(out2Core_reqServed_MIO_o_i),
    .out2Core_line_MIO_o(out2Core_line_MIO_o_i),
    .dma_intOut_o(dma_intOut_o_i)
);

endmodule
