#!/usr/bin/env python3
"""
ICache_Startup_Gen.py
---------------------
Generates a Verilog file containing a single `initial begin` block that
zeroes every ram8b8w$ cell in the ICache at simulation start.

Usage:
    python3 ICache_Startup_Gen.py <icache_conf.json>

Conf keys:
    readmemFilePath          – output filename  (e.g. "icache_loader.sv")
    outputPath               – directory to write the file into
    TagStoreCellPath_Lower   – hierarchical path to tag_store_ramCell_Lower
    TagStoreCellPath_Upper   – hierarchical path to tag_store_ramCell_Upper
    numDataStore_CellLayers  – LAYERS_OF_CELLS  (outer genvar i)
    numDataStoreCells        – NUM_CELLS / CACHE_LINES_SIZE_B  (inner genvar j)
    dataStoreCellPath        – path template; literal substrings
                               "<cell layer>" → replaced with i
                               "<cellNum>"    → replaced with j
    startUpDelay             – single delay inserted once at top of initial begin

Cell structure (ram8b8w$):
    8 words × 8 bits  →  mem[0] .. mem[7]

Generated Verilog is fully unrolled — no for-loops, no generate blocks.
Every mem[] assignment is an explicit statement so VCS has no issues.

Total writes emitted:
    2  (tag Lower + Upper, 8 words each)            =  16
    numDataStore_CellLayers × numDataStoreCells × 8  =  varies
"""

import json
import sys
from pathlib import Path

# Every ram8b8w$ has exactly 8 addressable words.
WORDS_PER_CELL = 8

REQUIRED_KEYS = [
    "readmemFilePath",
    "outputPath",
    "TagStoreCellPath_Lower",
    "TagStoreCellPath_Upper",
    "numDataStore_CellLayers",
    "numDataStoreCells",
    "dataStoreCellPath",
    "startUpDelay",
]

# ---------------------------------------------------------------------------
# Conf loader
# ---------------------------------------------------------------------------

def load_conf(path: str) -> dict:
    p = Path(path)
    if not p.exists():
        print(f"[ERROR] ICache_Startup_Gen: conf not found: {p}")
        sys.exit(1)
    try:
        conf = json.loads(p.read_text())
    except json.JSONDecodeError as exc:
        print(f"[ERROR] ICache_Startup_Gen: bad JSON in conf: {exc}")
        sys.exit(1)
    missing = [k for k in REQUIRED_KEYS if k not in conf]
    if missing:
        print(f"[ERROR] ICache_Startup_Gen: missing conf keys: {missing}")
        sys.exit(1)
    return conf

# ---------------------------------------------------------------------------
# Generation helpers
# ---------------------------------------------------------------------------

def _zero_cell_lines(hier_path: str) -> list[str]:
    """
    Return one fully-explicit assignment per word in a ram8b8w$ cell.
    No loops — each line is a standalone statement.
    """
    path = hier_path.strip()
    return [f"    {path}.mem[{w}] = 8'h00;" for w in range(WORDS_PER_CELL)]


def _resolve(template: str, layer: int, cell: int) -> str:
    return (template
            .replace("<cell layer>", str(layer))
            .replace("<cellNum>", str(cell)))

# ---------------------------------------------------------------------------
# Top-level generator
# ---------------------------------------------------------------------------

def generate(conf: dict) -> str:
    delay      = conf["startUpDelay"].strip()
    lower_path = conf["TagStoreCellPath_Lower"].strip()
    upper_path = conf["TagStoreCellPath_Upper"].strip()
    num_layers = int(conf["numDataStore_CellLayers"])
    num_cells  = int(conf["numDataStoreCells"])
    tmpl       = conf["dataStoreCellPath"].strip()

    lines: list[str] = []

    lines += [
        "// Auto-generated by ICache_Startup_Gen.py — do not edit by hand.",
        "// Zeroes every ram8b8w$ cell in the ICache at simulation start.",
        "// All assignments are fully unrolled (no loops) for VCS compatibility.",
        "",
        "initial begin",
        "",
        f"    #{delay};",
        "",
    ]

    # ── Tag Store – Lower ──────────────────────────────────────────────────
    lines.append("    // Tag Store – Lower")
    lines += _zero_cell_lines(lower_path)
    lines.append("")

    # ── Tag Store – Upper ──────────────────────────────────────────────────
    lines.append("    // Tag Store – Upper")
    lines += _zero_cell_lines(upper_path)
    lines.append("")

    # ── Data Store – fully unrolled over [layer][cell][word] ───────────────
    lines.append("    // Data Store")
    for i in range(num_layers):
        lines.append(f"    // g_mem_layer[{i}]")
        for j in range(num_cells):
            path = _resolve(tmpl, i, j)
            lines.append(f"    // g_memCells[{j}]")
            lines += _zero_cell_lines(path)
        lines.append("")

    lines += ["end", ""]

    return "\n".join(lines)

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: ICache_Startup_Gen.py <icache_conf.json>")
        return 2

    conf     = load_conf(sys.argv[1])
    out_dir  = Path(conf["outputPath"].strip())
    out_file = out_dir / conf["readmemFilePath"].strip()

    try:
        out_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        print(f"[ERROR] ICache_Startup_Gen: cannot create output dir {out_dir}: {exc}")
        return 1

    verilog = generate(conf)

    try:
        out_file.write_text(verilog)
    except OSError as exc:
        print(f"[ERROR] ICache_Startup_Gen: cannot write {out_file}: {exc}")
        return 1

    num_layers = int(conf["numDataStore_CellLayers"])
    num_cells  = int(conf["numDataStoreCells"])
    total      = (2 + num_layers * num_cells) * WORDS_PER_CELL

    print(f"[ICache_Startup_Gen] written → {out_file.resolve()}")
    print(f"  tag lower       : {conf['TagStoreCellPath_Lower'].strip()}")
    print(f"  tag upper       : {conf['TagStoreCellPath_Upper'].strip()}")
    print(f"  layers          : {num_layers}")
    print(f"  cells per layer : {num_cells}")
    print(f"  startup delay   : #{conf['startUpDelay'].strip()}")
    print(f"  total writes    : {total}  "
          f"(2 tag + {num_layers}×{num_cells} data) × {WORDS_PER_CELL} words")
    return 0


if __name__ == "__main__":
    sys.exit(main())
