#!/usr/bin/env python3
"""
csv_to_rom_verilog.py
---------------------
Converts a truth-table CSV into a structural Verilog module built from
rom64b32w$ instances (5-bit address, 64-bit output, active-high OE tristate).

CSV format
----------
  - Columns whose names end in "_i" are inputs.
  - Columns whose names end in "_o" are outputs.
  - All values must be 0 or 1.
  - Column order sets bit significance: leftmost input = MSB of the select/
    address vector; leftmost output = lowest DOUT bit index.
  - Missing input combinations default to output 0.

ROM tiling rules
----------------
  - The ROM has a 5-bit address → 32 words per ROM.
  - If there are more than 5 inputs  → upper (N-5) bits become the ROM-select
    signal; 2^(N-5) ROMs are instantiated and their OE lines are decoded.
  - If there are 5 or fewer inputs   → one ROM, OE tied high, unused address
    bits are zeroed.
  - If there are more than 64 output bits → multiple ROM banks, each bank
    handling 64 bits of the output vector; every bank gets the same set of
    ROM instances (one per select value) with its own dout_bus.

Usage
-----
  python csv_to_rom_verilog.py <input.csv> [output.v] [--module <name>]

  output.v  defaults to <input stem>.v
  --module  defaults to the output file stem
"""

import argparse
import csv
import math
import os
import sys
from pathlib import Path


# ── helpers ──────────────────────────────────────────────────────────────────

def parse_csv(path: str):
    """Return (inputs, outputs, mems).

    inputs  : list of input column names  (order = MSB first)
    outputs : list of output column names (order = bit-0 first)
    mems    : dict[(bank, sel, addr)] -> int  (output word for that bank)
    """
    with open(path, newline="") as fh:
        reader = csv.DictReader(fh)
        fieldnames = reader.fieldnames or []

        inputs  = [f for f in fieldnames if f.endswith("_i")]
        outputs = [f for f in fieldnames if f.endswith("_o")]

        if not inputs:
            sys.exit("ERROR: no input columns found (names must end in '_i')")
        if not outputs:
            sys.exit("ERROR: no output columns found (names must end in '_o')")

        n_in      = len(inputs)
        n_addr    = min(n_in, 5)
        n_sel     = n_in - n_addr          # upper bits → ROM select
        n_roms    = 2 ** n_sel             # number of ROM instances per bank
        n_out     = len(outputs)
        n_banks   = math.ceil(n_out / 64)  # how many 64-bit ROM banks

        # mems[bank][sel][addr] = 64-bit integer
        mems = [[[0] * 32 for _ in range(n_roms)] for _ in range(n_banks)]

        for row in reader:
            try:
                in_bits = [int(row[c]) for c in inputs]
            except (KeyError, ValueError) as e:
                sys.exit(f"ERROR parsing input row: {e}")

            sel_val  = int("".join(str(b) for b in in_bits[:n_sel]), 2) if n_sel else 0
            addr_val = int("".join(str(b) for b in in_bits[n_sel:]),  2)

            for bank in range(n_banks):
                word = 0
                for bit_idx in range(64):
                    out_idx = bank * 64 + bit_idx
                    if out_idx >= n_out:
                        break
                    try:
                        bit = int(row[outputs[out_idx]])
                    except (KeyError, ValueError):
                        bit = 0
                    word |= (bit << bit_idx)
                mems[bank][sel_val][addr_val] = word

    return inputs, outputs, n_roms, n_banks, n_addr, n_sel, mems


def indent(n: int) -> str:
    return "    " * n


# ── Verilog emitter ───────────────────────────────────────────────────────────

def emit_verilog(module_name, inputs, outputs,
                 n_roms, n_banks, n_addr, n_sel, mems) -> str:
    n_in  = len(inputs)
    n_out = len(outputs)
    lines = []
    w     = indent  # shorthand

    # ── header / module declaration ──────────────────────────────────────────
    lines += [
        f"// Auto-generated by csv_to_rom_verilog.py",
        f"// Module : {module_name}",
        f"// Inputs : {', '.join(inputs)}",
        f"// Outputs: {', '.join(outputs)}",
        f"// ROMs   : {n_roms} instance(s) per bank  x  {n_banks} bank(s)",
        f"//          ROM addr width = {n_addr} bit(s),  select width = {n_sel} bit(s)",
        f"`timescale 1ns/1ps",
        f"",
        f"module {module_name} (",
    ]

    port_lines = []
    for sig in inputs:
        port_lines.append(f"{w(1)}input  wire {sig}")
    for i, sig in enumerate(outputs):
        comma = "" if i == len(outputs) - 1 else ","
        port_lines.append(f"{w(1)}output wire {sig}{comma}")
    # fix commas: inputs all need trailing comma
    for i in range(len(inputs)):
        port_lines[i] += ","
    lines += port_lines
    lines += [");", ""]

    # ── address / select wires ───────────────────────────────────────────────
    addr_bits = "{" + ", ".join(inputs[n_sel:]) + "}"
    if n_addr == 1:
        addr_bits = inputs[n_sel]          # no braces needed for single bit

    zero_pad   = ["1'b0"] * (5 - n_addr)
    addr_parts = zero_pad + inputs[n_sel:]
    addr_concat = "{ " + ", ".join(addr_parts) + " }"

    if n_sel == 0:
        lines += [
            f"{w(1)}// Only {n_in} input bit(s) — single ROM, OE tied high",
            f"{w(1)}wire [4:0] addr = {addr_concat};",
            f"",
        ]
    else:
        sel_bits = "{ " + ", ".join(inputs[:n_sel]) + " }"
        lines += [
            f"{w(1)}// Address = lower {n_addr} input bit(s)",
            f"{w(1)}wire [4:0] addr = {addr_concat};",
            f"{w(1)}// Select  = upper {n_sel} input bit(s) → chooses which ROM drives the bus",
            f"{w(1)}wire [{n_sel-1}:0] sel = {sel_bits};",
            f"",
        ]

    # ── output assignment from dout_bus(es) ──────────────────────────────────
    for bank in range(n_banks):
        lines.append(f"{w(1)}// Bank {bank}: dout_bus_{bank} carries output bits [{min((bank+1)*64, n_out)-1}:{bank*64}]")
        lines.append(f"{w(1)}wire [63:0] dout_bus_{bank};")
    lines.append("")

    for out_idx, sig in enumerate(outputs):
        bank    = out_idx // 64
        bit_idx = out_idx % 64
        lines.append(f"{w(1)}assign {sig} = dout_bus_{bank}[{bit_idx}];")
    lines.append("")

    # ── ROM instances ─────────────────────────────────────────────────────────
    for bank in range(n_banks):
        lines.append(f"{w(1)}// {'─'*60}")
        lines.append(f"{w(1)}// Bank {bank}")
        lines.append(f"{w(1)}// {'─'*60}")
        lines.append("")

        for rom_idx in range(n_roms):
            if n_sel == 0:
                oe_expr = "1'b1"
                label   = "only ROM"
            else:
                sel_bin = format(rom_idx, f'0{n_sel}b')
                oe_expr = f"(sel == {n_sel}'d{rom_idx})"
                label   = f"sel == {n_sel}'b{sel_bin}"

            inst = f"u_rom_b{bank}_{rom_idx:02d}"

            lines += [
                f"{w(1)}// Bank {bank}, ROM {rom_idx:02d}  ({label})",
                f"{w(1)}wire oe_b{bank}_{rom_idx:02d} = {oe_expr};",
                f"{w(1)}rom64b32w$ {inst} (",
                f"{w(2)}.A    (addr),",
                f"{w(2)}.OE   (oe_b{bank}_{rom_idx:02d}),",
                f"{w(2)}.DOUT (dout_bus_{bank})",
                f"{w(1)});",
                f"{w(1)}initial begin",
            ]
            for addr in range(32):
                val = mems[bank][rom_idx][addr]
                lines.append(f"{w(2)}{inst}.mem[{addr:2d}] = 64'h{val:016X};")
            lines += [f"{w(1)}end", ""]

    lines += ["endmodule", ""]
    return "\n".join(lines)


# ── entry point ───────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Convert a truth-table CSV to a structural rom64b32w$ Verilog module."
    )
    parser.add_argument("csv",    help="Input CSV file")
    parser.add_argument("output", nargs="?", help="Output .v file (default: <csv_stem>.v)")
    parser.add_argument("--module", default="", help="Verilog module name (default: output file stem)")
    args = parser.parse_args()

    csv_path    = args.csv
    output_path = args.output or str(Path(csv_path).with_suffix(".v"))
    module_name = args.module or Path(output_path).stem

    if not os.path.isfile(csv_path):
        sys.exit(f"ERROR: file not found: {csv_path}")

    print(f"Parsing   : {csv_path}")
    inputs, outputs, n_roms, n_banks, n_addr, n_sel, mems = parse_csv(csv_path)

    print(f"Inputs    : {len(inputs)}  ({inputs})")
    print(f"Outputs   : {len(outputs)}  ({outputs})")
    print(f"Addr bits : {n_addr},  Select bits: {n_sel}")
    print(f"ROMs/bank : {n_roms},  Banks: {n_banks}  ({n_roms*n_banks} total instances)")

    verilog = emit_verilog(module_name, inputs, outputs,
                           n_roms, n_banks, n_addr, n_sel, mems)

    with open(output_path, "w") as fh:
        fh.write(verilog)

    print(f"Written   : {output_path}  ({len(verilog.splitlines())} lines)")


if __name__ == "__main__":
    main()