`define EXE_STAGE \
EXE execute_unit ( \
    .clk(clk), \
    .rst(rst), \
    .latches_valid                     (exe_latches_valid), \
    .latches_cs_ST_OP                  (exe_latches_cs_ST_OP), \
    .latches_cs_OP_TYPE                (exe_latches_cs_OP_TYPE), \
    .latches_cs_alu_inputA_sel         (exe_latches_cs_alu_inputA_sel), \
    .latches_cs_alu_inputA_sel_b       (exe_latches_cs_alu_inputA_sel_b), \
    .latches_cs_alu_inputA_sel_c       (exe_latches_cs_alu_inputA_sel_c), \
    .latches_cs_alu_inputB_sel         (exe_latches_cs_alu_inputB_sel), \
    .latches_cs_alu_inputB_sel_b       (exe_latches_cs_alu_inputB_sel_b), \
    .latches_cs_alu_inputB_sel_c       (exe_latches_cs_alu_inputB_sel_c), \
    .latches_cs_branch_target_sel      (exe_latches_cs_branch_target_sel), \
    .latches_cs_branch_target_sel_b    (exe_latches_cs_branch_target_sel_b), \
    .latches_cs_branch_target_sel_c    (exe_latches_cs_branch_target_sel_c), \
    .latches_cs_shift_by_one           (exe_latches_cs_shift_by_one), \
    .latches_cs_br_ucond               (exe_latches_cs_br_ucond), \
    .latches_cs_relative_branch        (exe_latches_cs_relative_branch), \
    .latches_cs_special_br             (exe_latches_cs_special_br), \
    .latches_cs_is_far                 (exe_latches_cs_is_far), \
    .latches_cs_is_call                (exe_latches_cs_is_call), \
    .latches_cs_second_flag_needed     (exe_latches_cs_second_flag_needed), \
    .latches_cs_rep_no_zf_update       (exe_latches_cs_rep_no_zf_update), \
    .latches_wb_cs_ST_OP               (exe_latches_wb_cs_ST_OP), \
    .latches_wb_cs_WB_DR               (exe_latches_wb_cs_WB_DR), \
    .latches_wb_cs_WB_SR               (exe_latches_wb_cs_WB_SR), \
    .latches_wb_cs_WB_EAX              (exe_latches_wb_cs_WB_EAX), \
    .latches_data_size_vec             (exe_latches_data_size_vec), \
    .latches_sr_data_size_vec          (exe_latches_sr_data_size_vec), \
    .latches_shift_sr_up               (exe_latches_shift_sr_up), \
    .latches_shift_sr_down             (exe_latches_shift_sr_down), \
    .latches_ST_XCL                    (exe_latches_ST_XCL), \
    .latches_ST_PADDR_0                (exe_latches_ST_PADDR_0), \
    .latches_ST_PADDR_1                (exe_latches_ST_PADDR_1), \
    .latches_MIO                       (exe_latches_MIO), \
    .latches_br_info_valid             (exe_latches_br_info_valid), \
    .latches_br_info_br_eip            (exe_latches_br_info_br_eip), \
    .latches_br_info_br_xcl            (exe_latches_br_info_br_xcl), \
    .latches_br_info_br_pred_taken    (exe_latches_br_info_br_pred_taken), \
    .latches_br_info_speculative_target(exe_latches_br_info_speculative_target), \
    .latches_br_rel_target             (exe_latches_br_rel_target), \
    .latches_NEIP                      (exe_latches_NEIP), \
    .latches_EIP                       (exe_latches_EIP), \
    .latches_EAX                       (exe_latches_EAX), \
    .latches_imm64                     (exe_latches_imm64), \
    .latches_ld_buf                    (exe_latches_ld_buf), \
    .latches_sr_id                     (exe_latches_sr_id), \
    .latches_sr_data                   (exe_latches_sr_data), \
    .latches_dr_id                     (exe_latches_dr_id), \
    .latches_dr_data                   (exe_latches_dr_data), \
    .latches_ld_addy                   (exe_latches_ld_addy), \
    .wb_outs_wb_stall                  (wb_outputs_wb_stall), \
    .rr_outs_codeSeg_data              (rr_outputs_codeSeg_data), \
    .rr_outs_regFileValues_0           (rr_outputs_regFileValues_0), \
    .rr_outs_regFileValues_1           (rr_outputs_regFileValues_1), \
    .rr_outs_regFileValues_2           (rr_outputs_regFileValues_2), \
    .rr_outs_regFileValues_3           (rr_outputs_regFileValues_3), \
    .rr_outs_regFileValues_4           (rr_outputs_regFileValues_4), \
    .rr_outs_regFileValues_5           (rr_outputs_regFileValues_5), \
    .rr_outs_regFileValues_6           (rr_outputs_regFileValues_6), \
    .rr_outs_regFileValues_7           (rr_outputs_regFileValues_7), \
    .rr_outs_regFileValues_8           (rr_outputs_regFileValues_8), \
    .rr_outs_regFileValues_9           (rr_outputs_regFileValues_9), \
    .rr_outs_regFileValues_10          (rr_outputs_regFileValues_10), \
    .rr_outs_regFileValues_11          (rr_outputs_regFileValues_11), \
    .rr_outs_regFileValues_12          (rr_outputs_regFileValues_12), \
    .rr_outs_regFileValues_13          (rr_outputs_regFileValues_13), \
    .rr_outs_regFileValues_14          (rr_outputs_regFileValues_14), \
    .rr_outs_regFileValues_15          (rr_outputs_regFileValues_15), \
    .rr_outs_regFileValues_16          (rr_outputs_regFileValues_16), \
    .rr_outs_regFileValues_17          (rr_outputs_regFileValues_17), \
    .rr_outs_regFileValues_18          (rr_outputs_regFileValues_18), \
    .rr_outs_regFileValues_19          (rr_outputs_regFileValues_19), \
    .rr_outs_regFileValues_20          (rr_outputs_regFileValues_20), \
    .rr_outs_regFileValues_21          (rr_outputs_regFileValues_21), \
    .rr_outs_regFileValues_22          (rr_outputs_regFileValues_22), \
    .rr_outs_regFileValues_23          (rr_outputs_regFileValues_23), \
    .rr_outs_regFileValues_24          (rr_outputs_regFileValues_24), \
    .rr_outs_regFileValues_25          (rr_outputs_regFileValues_25), \
    .wb_latches_next_valid             (wb_latches_next_valid), \
    .wb_latches_next_cs_ST_OP          (wb_latches_next_cs_ST_OP), \
    .wb_latches_next_cs_WB_DR          (wb_latches_next_cs_WB_DR), \
    .wb_latches_next_cs_WB_SR          (wb_latches_next_cs_WB_SR), \
    .wb_latches_next_cs_WB_EAX         (wb_latches_next_cs_WB_EAX), \
    .wb_latches_next_ST_XCL            (wb_latches_next_ST_XCL), \
    .wb_latches_next_ST_PADDR_0        (wb_latches_next_ST_PADDR_0), \
    .wb_latches_next_ST_BIT_VEC_0      (wb_latches_next_ST_BIT_VEC_0), \
    .wb_latches_next_ST_PADDR_1        (wb_latches_next_ST_PADDR_1), \
    .wb_latches_next_ST_BIT_VEC_1      (wb_latches_next_ST_BIT_VEC_1), \
    .wb_latches_next_MIO               (wb_latches_next_MIO), \
    .wb_latches_next_EIP               (wb_latches_next_EIP), \
    .wb_latches_next_res_buf           (wb_latches_next_res_buf), \
    .wb_latches_next_sr_id             (wb_latches_next_sr_id), \
    .wb_latches_next_sr_data           (wb_latches_next_sr_data), \
    .wb_latches_next_dr_id             (wb_latches_next_dr_id), \
    .wb_latches_next_dr_data           (wb_latches_next_dr_data), \
    .wb_latches_next_EAX               (wb_latches_next_EAX), \
    .outs_valid                        (exe_outputs_valid), \
    .outs_br_res_valid                 (exe_outputs_br_res_valid), \
    .outs_br_res_flush                 (exe_outputs_br_res_flush), \
    .outs_br_res_farFlush              (exe_outputs_br_res_farFlush), \
    .outs_br_res_callFlush             (exe_outputs_br_res_callFlush), \
    .outs_br_res_miss_prediction       (exe_outputs_br_res_miss_prediction), \
    .outs_br_res_br_eip                (exe_outputs_br_res_br_eip), \
    .outs_br_res_neip                  (exe_outputs_br_res_neip), \
    .outs_br_res_br_target             (exe_outputs_br_res_br_target), \
    .outs_br_res_taken                 (exe_outputs_br_res_taken), \
    .outs_br_res_br_XCL                (exe_outputs_br_res_br_XCL), \
    .outs_br_res_clr_exp_mode          (exe_outputs_br_res_clr_exp_mode), \
    .outs_br_res_br_ucond              (exe_outputs_br_res_br_ucond), \
    .outs_DR_0_we                      (exe_outputs_DR_0_we), \
    .outs_DR_0_id                      (exe_outputs_DR_0_id), \
    .outs_DR_0_data                    (exe_outputs_DR_0_data), \
    .outs_DR_1_we                      (exe_outputs_DR_1_we), \
    .outs_DR_1_id                      (exe_outputs_DR_1_id), \
    .outs_DR_1_data                    (exe_outputs_DR_1_data), \
    .outs_clr_ZF_sb                    (exe_outputs_clr_ZF_sb), \
    .outs_ZF                           (exe_outputs_ZF), \
    .outs_ST_OP                        (exe_outputs_ST_OP), \
    .outs_ST_XCL                       (exe_outputs_ST_XCL), \
    .outs_ST_PADDR_0                   (exe_outputs_ST_PADDR_0), \
    .outs_ST_PADDR_1                   (exe_outputs_ST_PADDR_1), \
    .outs_wb_stage_latch_we            (exe_outputs_wb_stage_latch_we) \
);
