`define FETCH_STAGE \
    Fetch fetch_unit ( \
        .clk(clk), \
        .rst(rst), \
        .icache_info_hit              (out_hit), \
        .icache_info_instruction_line (out_instruction_line), \
        .idm_info_idm_slots_0_valid         (idm_outputs_idm_slots_0_valid), \
        .idm_info_idm_slots_0_br_valid      (idm_outputs_idm_slots_0_br_valid), \
        .idm_info_idm_slots_0_br_eip        (idm_outputs_idm_slots_0_br_eip), \
        .idm_info_idm_slots_0_br_btb_target (idm_outputs_idm_slots_0_br_btb_target), \
        .idm_info_idm_slots_0_br_xcl        (idm_outputs_idm_slots_0_br_xcl), \
        .idm_info_idm_slots_1_valid         (idm_outputs_idm_slots_1_valid), \
        .idm_info_idm_slots_1_br_valid      (idm_outputs_idm_slots_1_br_valid), \
        .idm_info_idm_slots_1_br_eip        (idm_outputs_idm_slots_1_br_eip), \
        .idm_info_idm_slots_1_br_btb_target (idm_outputs_idm_slots_1_br_btb_target), \
        .idm_info_idm_slots_1_br_xcl        (idm_outputs_idm_slots_1_br_xcl), \
        .idm_info_idm_slots_2_valid         (idm_outputs_idm_slots_2_valid), \
        .idm_info_idm_slots_2_br_valid      (idm_outputs_idm_slots_2_br_valid), \
        .idm_info_idm_slots_2_br_eip        (idm_outputs_idm_slots_2_br_eip), \
        .idm_info_idm_slots_2_br_btb_target (idm_outputs_idm_slots_2_br_btb_target), \
        .idm_info_idm_slots_2_br_xcl        (idm_outputs_idm_slots_2_br_xcl), \
        .idm_info_idm_slots_3_valid         (idm_outputs_idm_slots_3_valid), \
        .idm_info_idm_slots_3_br_valid      (idm_outputs_idm_slots_3_br_valid), \
        .idm_info_idm_slots_3_br_eip        (idm_outputs_idm_slots_3_br_eip), \
        .idm_info_idm_slots_3_br_btb_target (idm_outputs_idm_slots_3_br_btb_target), \
        .idm_info_idm_slots_3_br_xcl        (idm_outputs_idm_slots_3_br_xcl), \
        .idm_info_valid_slots               (idm_outputs_valid_slots), \
        .decode_outs_invalid_instruction (decode_outputs_invalid_instruction), \
        .decode_outs_eip                 (decode_outputs_eip), \
        .decode_outs_decode_forward      (decode_outputs_decode_forward), \
        .decode_outs_stall               (decode_outputs_stall), \
        .rr_outs_valid          (rr_outputs_valid), \
        .rr_outs_codeSeg_sb     (rr_outputs_codeSeg_sb), \
        .rr_outs_codeSeg_data   (rr_outputs_codeSeg_data), \
        .rr_outs_codeSeg_limit  (rr_outputs_codeSeg_limit), \
        .dc_outs_valid       (dc_outputs_valid), \
        .dc_outs_exp_present (dc_outputs_exp_present), \
        .dc_outs_exp_pf      (dc_outputs_exp_pf), \
        .mem_outs_valid (mem_outputs_valid), \
        .exe_outs_valid                   (exe_outputs_valid), \
        .exe_outs_br_res_valid_btb        (exe_outputs_br_res_valid_btb), \
        .exe_outs_br_res_valid_pred       (exe_outputs_br_res_valid_pred), \
        .exe_outs_br_res_valid_fetch      (exe_outputs_br_res_valid_fetch), \
        .exe_outs_br_res_flush            (exe_outputs_br_res_flush_fetch), \
        .exe_outs_br_res_miss_prediction_pred  (exe_outputs_br_res_miss_prediction_pred), \
        .exe_outs_br_res_br_eip           (exe_outputs_br_res_br_eip), \
        .exe_outs_br_res_neip             (exe_outputs_br_res_neip), \
        .exe_outs_br_res_br_target        (exe_outputs_br_res_br_target), \
        .exe_outs_br_res_taken            (exe_outputs_br_res_taken), \
        .exe_outs_br_res_br_XCL           (exe_outputs_br_res_br_XCL), \
        .exe_outs_br_res_clr_exp_mode     (exe_outputs_br_res_clr_exp_mode), \
        .exe_outs_br_res_br_ucond         (exe_outputs_br_res_br_ucond), \
        .wb_outs_valid (wb_outputs_valid), \
        .dma_int (inFromDMA_i), \
        .outs_fetch_2_icache_icache_en           (fetch_outputs_fetch_2_icache_icache_en), \
        .outs_fetch_2_icache_p_addr              (fetch_outputs_fetch_2_icache_p_addr), \
        .outs_fetch_2_icache_v_addr_i            (fetch_outputs_fetch_2_icache_v_addr_i), \
        .outs_fetch_2_icache_num_valid_IDM_slots (fetch_outputs_fetch_2_icache_num_valid_IDM_slots), \
        .outs_idm_reqs_req_0_ld_meta_data (fetch_outputs_idm_reqs_req_0_ld_meta_data), \
        .outs_idm_reqs_req_0_ld_data      (fetch_outputs_idm_reqs_req_0_ld_data), \
        .outs_idm_reqs_req_0_valid        (fetch_outputs_idm_reqs_req_0_valid), \
        .outs_idm_reqs_req_0_br_valid     (fetch_outputs_idm_reqs_req_0_br_valid), \
        .outs_idm_reqs_req_0_br_eip       (fetch_outputs_idm_reqs_req_0_br_eip), \
        .outs_idm_reqs_req_0_br_target    (fetch_outputs_idm_reqs_req_0_br_target), \
        .outs_idm_reqs_req_0_br_xcl       (fetch_outputs_idm_reqs_req_0_br_xcl), \
        .outs_idm_reqs_req_0_data         (fetch_outputs_idm_reqs_req_0_data), \
        .outs_idm_reqs_req_1_ld_meta_data (fetch_outputs_idm_reqs_req_1_ld_meta_data), \
        .outs_idm_reqs_req_1_ld_data      (fetch_outputs_idm_reqs_req_1_ld_data), \
        .outs_idm_reqs_req_1_valid        (fetch_outputs_idm_reqs_req_1_valid), \
        .outs_idm_reqs_req_1_br_valid     (fetch_outputs_idm_reqs_req_1_br_valid), \
        .outs_idm_reqs_req_1_br_eip       (fetch_outputs_idm_reqs_req_1_br_eip), \
        .outs_idm_reqs_req_1_br_target    (fetch_outputs_idm_reqs_req_1_br_target), \
        .outs_idm_reqs_req_1_br_xcl       (fetch_outputs_idm_reqs_req_1_br_xcl), \
        .outs_idm_reqs_req_1_data         (fetch_outputs_idm_reqs_req_1_data), \
        .outs_idm_reqs_req_2_ld_meta_data (fetch_outputs_idm_reqs_req_2_ld_meta_data), \
        .outs_idm_reqs_req_2_ld_data      (fetch_outputs_idm_reqs_req_2_ld_data), \
        .outs_idm_reqs_req_2_valid        (fetch_outputs_idm_reqs_req_2_valid), \
        .outs_idm_reqs_req_2_br_valid     (fetch_outputs_idm_reqs_req_2_br_valid), \
        .outs_idm_reqs_req_2_br_eip       (fetch_outputs_idm_reqs_req_2_br_eip), \
        .outs_idm_reqs_req_2_br_target    (fetch_outputs_idm_reqs_req_2_br_target), \
        .outs_idm_reqs_req_2_br_xcl       (fetch_outputs_idm_reqs_req_2_br_xcl), \
        .outs_idm_reqs_req_2_data         (fetch_outputs_idm_reqs_req_2_data), \
        .outs_idm_reqs_req_3_ld_meta_data (fetch_outputs_idm_reqs_req_3_ld_meta_data), \
        .outs_idm_reqs_req_3_ld_data      (fetch_outputs_idm_reqs_req_3_ld_data), \
        .outs_idm_reqs_req_3_valid        (fetch_outputs_idm_reqs_req_3_valid), \
        .outs_idm_reqs_req_3_br_valid     (fetch_outputs_idm_reqs_req_3_br_valid), \
        .outs_idm_reqs_req_3_br_eip       (fetch_outputs_idm_reqs_req_3_br_eip), \
        .outs_idm_reqs_req_3_br_target    (fetch_outputs_idm_reqs_req_3_br_target), \
        .outs_idm_reqs_req_3_br_xcl       (fetch_outputs_idm_reqs_req_3_br_xcl), \
        .outs_idm_reqs_req_3_data         (fetch_outputs_idm_reqs_req_3_data), \
        .outs_exp_pipe_clear (fetch_outputs_exp_pipe_clear), \
        .outs_exp_present    (fetch_outputs_exp_present), \
        .outs_exp_pf         (fetch_outputs_exp_pf), \
        .outs_exp_mode_jk    (fetch_outputs_exp_mode_jk), \
        .outs_int_mode_jk    (fetch_outputs_int_mode_jk) \
    );
