`define IDM_STAGE \
    IDM idm_unit ( \
        .clk(clk), \
        .rst(rst), \
        .fetch_outs_exp_pipe_clear              (fetch_outputs_exp_pipe_clear), \
        .fetch_outs_idm_reqs_req_0_ld_meta_data (fetch_outputs_idm_reqs_req_0_ld_meta_data), \
        .fetch_outs_idm_reqs_req_0_ld_data      (fetch_outputs_idm_reqs_req_0_ld_data), \
        .fetch_outs_idm_reqs_req_0_valid        (fetch_outputs_idm_reqs_req_0_valid), \
        .fetch_outs_idm_reqs_req_0_br_valid     (fetch_outputs_idm_reqs_req_0_br_valid), \
        .fetch_outs_idm_reqs_req_0_br_eip       (fetch_outputs_idm_reqs_req_0_br_eip), \
        .fetch_outs_idm_reqs_req_0_br_target    (fetch_outputs_idm_reqs_req_0_br_target), \
        .fetch_outs_idm_reqs_req_0_br_xcl       (fetch_outputs_idm_reqs_req_0_br_xcl), \
        .fetch_outs_idm_reqs_req_0_data         (fetch_outputs_idm_reqs_req_0_data), \
        .fetch_outs_idm_reqs_req_1_ld_meta_data (fetch_outputs_idm_reqs_req_1_ld_meta_data), \
        .fetch_outs_idm_reqs_req_1_ld_data      (fetch_outputs_idm_reqs_req_1_ld_data), \
        .fetch_outs_idm_reqs_req_1_valid        (fetch_outputs_idm_reqs_req_1_valid), \
        .fetch_outs_idm_reqs_req_1_br_valid     (fetch_outputs_idm_reqs_req_1_br_valid), \
        .fetch_outs_idm_reqs_req_1_br_eip       (fetch_outputs_idm_reqs_req_1_br_eip), \
        .fetch_outs_idm_reqs_req_1_br_target    (fetch_outputs_idm_reqs_req_1_br_target), \
        .fetch_outs_idm_reqs_req_1_br_xcl       (fetch_outputs_idm_reqs_req_1_br_xcl), \
        .fetch_outs_idm_reqs_req_1_data         (fetch_outputs_idm_reqs_req_1_data), \
        .fetch_outs_idm_reqs_req_2_ld_meta_data (fetch_outputs_idm_reqs_req_2_ld_meta_data), \
        .fetch_outs_idm_reqs_req_2_ld_data      (fetch_outputs_idm_reqs_req_2_ld_data), \
        .fetch_outs_idm_reqs_req_2_valid        (fetch_outputs_idm_reqs_req_2_valid), \
        .fetch_outs_idm_reqs_req_2_br_valid     (fetch_outputs_idm_reqs_req_2_br_valid), \
        .fetch_outs_idm_reqs_req_2_br_eip       (fetch_outputs_idm_reqs_req_2_br_eip), \
        .fetch_outs_idm_reqs_req_2_br_target    (fetch_outputs_idm_reqs_req_2_br_target), \
        .fetch_outs_idm_reqs_req_2_br_xcl       (fetch_outputs_idm_reqs_req_2_br_xcl), \
        .fetch_outs_idm_reqs_req_2_data         (fetch_outputs_idm_reqs_req_2_data), \
        .fetch_outs_idm_reqs_req_3_ld_meta_data (fetch_outputs_idm_reqs_req_3_ld_meta_data), \
        .fetch_outs_idm_reqs_req_3_ld_data      (fetch_outputs_idm_reqs_req_3_ld_data), \
        .fetch_outs_idm_reqs_req_3_valid        (fetch_outputs_idm_reqs_req_3_valid), \
        .fetch_outs_idm_reqs_req_3_br_valid     (fetch_outputs_idm_reqs_req_3_br_valid), \
        .fetch_outs_idm_reqs_req_3_br_eip       (fetch_outputs_idm_reqs_req_3_br_eip), \
        .fetch_outs_idm_reqs_req_3_br_target    (fetch_outputs_idm_reqs_req_3_br_target), \
        .fetch_outs_idm_reqs_req_3_br_xcl       (fetch_outputs_idm_reqs_req_3_br_xcl), \
        .fetch_outs_idm_reqs_req_3_data         (fetch_outputs_idm_reqs_req_3_data), \
        .idm_outs_idm_slots_0_valid         (idm_outputs_idm_slots_0_valid), \
        .idm_outs_idm_slots_0_br_valid      (idm_outputs_idm_slots_0_br_valid), \
        .idm_outs_idm_slots_0_br_eip        (idm_outputs_idm_slots_0_br_eip), \
        .idm_outs_idm_slots_0_br_btb_target (idm_outputs_idm_slots_0_br_btb_target), \
        .idm_outs_idm_slots_0_br_xcl        (idm_outputs_idm_slots_0_br_xcl), \
        .idm_outs_idm_slots_0_data          (idm_outputs_idm_slots_0_data), \
        .idm_outs_idm_slots_1_valid         (idm_outputs_idm_slots_1_valid), \
        .idm_outs_idm_slots_1_br_valid      (idm_outputs_idm_slots_1_br_valid), \
        .idm_outs_idm_slots_1_br_eip        (idm_outputs_idm_slots_1_br_eip), \
        .idm_outs_idm_slots_1_br_btb_target (idm_outputs_idm_slots_1_br_btb_target), \
        .idm_outs_idm_slots_1_br_xcl        (idm_outputs_idm_slots_1_br_xcl), \
        .idm_outs_idm_slots_1_data          (idm_outputs_idm_slots_1_data), \
        .idm_outs_idm_slots_2_valid         (idm_outputs_idm_slots_2_valid), \
        .idm_outs_idm_slots_2_br_valid      (idm_outputs_idm_slots_2_br_valid), \
        .idm_outs_idm_slots_2_br_eip        (idm_outputs_idm_slots_2_br_eip), \
        .idm_outs_idm_slots_2_br_btb_target (idm_outputs_idm_slots_2_br_btb_target), \
        .idm_outs_idm_slots_2_br_xcl        (idm_outputs_idm_slots_2_br_xcl), \
        .idm_outs_idm_slots_2_data          (idm_outputs_idm_slots_2_data), \
        .idm_outs_idm_slots_3_valid         (idm_outputs_idm_slots_3_valid), \
        .idm_outs_idm_slots_3_br_valid      (idm_outputs_idm_slots_3_br_valid), \
        .idm_outs_idm_slots_3_br_eip        (idm_outputs_idm_slots_3_br_eip), \
        .idm_outs_idm_slots_3_br_btb_target (idm_outputs_idm_slots_3_br_btb_target), \
        .idm_outs_idm_slots_3_br_xcl        (idm_outputs_idm_slots_3_br_xcl), \
        .idm_outs_idm_slots_3_data          (idm_outputs_idm_slots_3_data), \
        .idm_outs_valid_slots (idm_outputs_valid_slots) \
    );
