`define MEM_STAGE

module MEM (
    .clk(clk),
    .rst(rst),

    .latches_valid(mem_latches_valid),
    .latches_cs_ST_OP(mem_latches_cs_ST_OP),
    .latches_cs_LD_OP(mem_latches_cs_LD_OP),
    .latches_exe_cs_ST_OP(mem_latches_exe_cs_ST_OP),
    .latches_exe_cs_OP_TYPE(mem_latches_exe_cs_OP_TYPE),
    .latches_exe_cs_alu_inputA_sel(mem_latches_exe_cs_alu_inputA_sel),
    .latches_exe_cs_alu_inputB_sel(mem_latches_exe_cs_alu_inputB_sel),
    .latches_exe_cs_branch_target_sel(mem_latches_exe_cs_branch_target_sel),
    .latches_exe_cs_shift_by_one(mem_latches_exe_cs_shift_by_one),
    .latches_exe_cs_br_ucond(mem_latches_exe_cs_br_ucond),
    .latches_exe_cs_relative_branch(mem_latches_exe_cs_relative_branch),
    .latches_exe_cs_special_br(mem_latches_exe_cs_special_br),
    .latches_exe_cs_is_far(mem_latches_exe_cs_is_far),
    .latches_exe_cs_is_call(mem_latches_exe_cs_is_call),
    .latches_exe_cs_second_flag_needed(mem_latches_exe_cs_second_flag_needed),
    .latches_exe_cs_rep_no_zf_update(mem_latches_exe_cs_rep_no_zf_update),
    .latches_wb_cs_ST_OP(mem_latches_wb_cs_ST_OP),
    .latches_wb_cs_WB_DR(mem_latches_wb_cs_WB_DR),
    .latches_wb_cs_WB_SR(mem_latches_wb_cs_WB_SR),
    .latches_wb_cs_WB_EAX(mem_latches_wb_cs_WB_EAX),
    .latches_br_info_valid(mem_latches_br_info_valid),
    .latches_br_info_br_eip(mem_latches_br_info_br_eip),
    .latches_br_info_br_xcl(mem_latches_br_info_br_xcl),
    .latches_br_info_br_pred_taken(mem_latches_br_info_br_pred_taken),
    .latches_br_info_speculative_target(mem_latches_br_info_speculative_target),
    .latches_data_size_vec(mem_latches_data_size_vec),
    .latches_sr_data_size_vec(mem_latches_sr_data_size_vec),
    .latches_shift_sr_up(mem_latches_shift_sr_up),
    .latches_shift_sr_down(mem_latches_shift_sr_down),
    .latches_ST_XCL(mem_latches_ST_XCL),
    .latches_ST_PADDR_0(mem_latches_ST_PADDR_0),
    .latches_ST_PADDR_1(mem_latches_ST_PADDR_1),
    .latches_MIO(mem_latches_MIO),
    .latches_NEIP(mem_latches_NEIP),
    .latches_EIP(mem_latches_EIP),
    .latches_EAX(mem_latches_EAX),
    .latches_imm64(mem_latches_imm64),
    .latches_sr_id(mem_latches_sr_id),
    .latches_sr_data(mem_latches_sr_data),
    .latches_dr_id(mem_latches_dr_id),
    .latches_dr_data(mem_latches_dr_data),
    .latches_LD_XCL(mem_latches_LD_XCL),
    .latches_swapLines(mem_latches_swapLines),
    .latches_LD_PADDR_0(mem_latches_LD_PADDR_0),
    .latches_LD_PADDR_1(mem_latches_LD_PADDR_1),

    .exe_outs_valid(exe_outputs_valid),
    .exe_outs_br_res_flush(exe_outputs_br_res_flush),

    .wb_outs_wb_stall(wb_outputs_wb_stall),

    .hit_0(dcache2Core_hit_0_o),
    .hit_1(dcache2Core_hit_1_o),
    .hit_2(dcache2Core_hit_2_o),
    .hit_3(dcache2Core_hit_3_o),
    .cacheline_0(dcache2Core_cacheline_0_o),
    .cacheline_1(dcache2Core_cacheline_1_o),
    .cacheline_2(dcache2Core_cacheline_2_o),
    .cacheline_3(dcache2Core_cacheline_3_o),
    .hit_MIO(dcache2Core_hit_MIO_o),
    .line_MIO(dcache2Core_line_MIO_o),

    .exe_latches_next_valid(exe_latches_next_valid),
    .exe_latches_next_cs_ST_OP(exe_latches_next_cs_ST_OP),
    .exe_latches_next_cs_OP_TYPE(exe_latches_next_cs_OP_TYPE),
    .exe_latches_next_cs_alu_inputA_sel(exe_latches_next_cs_alu_inputA_sel),
    .exe_latches_next_cs_alu_inputB_sel(exe_latches_next_cs_alu_inputB_sel),
    .exe_latches_next_cs_branch_target_sel(exe_latches_next_cs_branch_target_sel),
    .exe_latches_next_cs_shift_by_one(exe_latches_next_cs_shift_by_one),
    .exe_latches_next_cs_br_ucond(exe_latches_next_cs_br_ucond),
    .exe_latches_next_cs_relative_branch(exe_latches_next_cs_relative_branch),
    .exe_latches_next_cs_special_br(exe_latches_next_cs_special_br),
    .exe_latches_next_cs_is_far(exe_latches_next_cs_is_far),
    .exe_latches_next_cs_is_call(exe_latches_next_cs_is_call),
    .exe_latches_next_cs_second_flag_needed(exe_latches_next_cs_second_flag_needed),
    .exe_latches_next_cs_rep_no_zf_update(exe_latches_next_cs_rep_no_zf_update),
    .exe_latches_next_wb_cs_ST_OP(exe_latches_next_wb_cs_ST_OP),
    .exe_latches_next_wb_cs_WB_DR(exe_latches_next_wb_cs_WB_DR),
    .exe_latches_next_wb_cs_WB_SR(exe_latches_next_wb_cs_WB_SR),
    .exe_latches_next_wb_cs_WB_EAX(exe_latches_next_wb_cs_WB_EAX),
    .exe_latches_next_data_size_vec(exe_latches_next_data_size_vec),
    .exe_latches_next_sr_data_size_vec(exe_latches_next_sr_data_size_vec),
    .exe_latches_next_shift_sr_up(exe_latches_next_shift_sr_up),
    .exe_latches_next_shift_sr_down(exe_latches_next_shift_sr_down),
    .exe_latches_next_ST_XCL(exe_latches_next_ST_XCL),
    .exe_latches_next_ST_PADDR_0(exe_latches_next_ST_PADDR_0),
    .exe_latches_next_ST_PADDR_1(exe_latches_next_ST_PADDR_1),
    .exe_latches_next_MIO(exe_latches_next_MIO),
    .exe_latches_next_br_info_valid(exe_latches_next_br_info_valid),
    .exe_latches_next_br_info_br_eip(exe_latches_next_br_info_br_eip),
    .exe_latches_next_br_info_br_xcl(exe_latches_next_br_info_br_xcl),
    .exe_latches_next_br_info_br_pred_taken(exe_latches_next_br_info_br_pred_taken),
    .exe_latches_next_br_info_speculative_target(exe_latches_next_br_info_speculative_target),
    .exe_latches_next_br_rel_target(exe_latches_next_br_rel_target),
    .exe_latches_next_NEIP(exe_latches_next_NEIP),
    .exe_latches_next_EIP(exe_latches_next_EIP),
    .exe_latches_next_EAX(exe_latches_next_EAX),
    .exe_latches_next_imm64(exe_latches_next_imm64),
    .exe_latches_next_ld_buf(exe_latches_next_ld_buf),
    .exe_latches_next_sr_id(exe_latches_next_sr_id),
    .exe_latches_next_sr_data(exe_latches_next_sr_data),
    .exe_latches_next_dr_id(exe_latches_next_dr_id),
    .exe_latches_next_dr_data(exe_latches_next_dr_data),
    .exe_latches_next_ld_addy(exe_latches_next_ld_addy),
    .outs_valid(mem_outputs_valid),
    .outs_stall(mem_outputs_stall),

    .outs_ST_XCL(mem_outputs_ST_XCL),
    .outs_ST_PADDR_0(mem_outputs_ST_PADDR_0),
    .outs_ST_PADDR_1(mem_outputs_ST_PADDR_1),
    .outs_ST_OP(mem_outputs_ST_OP),

    .outs_exe_stage_latch_we(mem_outputs_exe_stage_latch_we),

    .outs_clr_dcache_arb_latches_0(core_memStage_CLR_REQ_0_i),
    .outs_clr_dcache_arb_latches_1(core_memStage_CLR_REQ_1_i),
    .outs_clr_dcache_arb_latches_2(core_memStage_CLR_REQ_2_i),
    .outs_clr_dcache_arb_latches_3(core_memStage_CLR_REQ_3_i),

    .outs_clr_dcache_mio_latch(core_memStage_CLR_REQ_MIO_i)
);
