`define RR_STAGE \
    RR rr_unit ( \
        .clk(clk), \
        .rst(rst), \
        .latches_normal_latches_valid                  (rr_latches_normal_valid), \
        .latches_normal_latches_cs_ST_SEL              (rr_latches_normal_cs_ST_SEL), \
        .latches_normal_latches_cs_MODRM_NEEDED        (rr_latches_normal_cs_MODRM_NEEDED), \
        .latches_normal_latches_cs_RM_IS_DR            (rr_latches_normal_cs_RM_IS_DR), \
        .latches_normal_latches_cs_SWITCH_LD_ADDY      (rr_latches_normal_cs_SWITCH_LD_ADDY), \
        .latches_normal_latches_cs_LD_OP               (rr_latches_normal_cs_LD_OP), \
        .latches_normal_latches_cs_ST_OP               (rr_latches_normal_cs_ST_OP), \
        .latches_normal_latches_cs_dr_id               (rr_latches_normal_cs_dr_id), \
        .latches_normal_latches_cs_sr_id               (rr_latches_normal_cs_sr_id), \
        .latches_normal_latches_cs_dr_rd               (rr_latches_normal_cs_dr_rd), \
        .latches_normal_latches_cs_sr_rd               (rr_latches_normal_cs_sr_rd), \
        .latches_normal_latches_cs_eax_rd              (rr_latches_normal_cs_eax_rd), \
        .latches_normal_latches_cs_dr_wr               (rr_latches_normal_cs_dr_wr), \
        .latches_normal_latches_cs_sr_wr               (rr_latches_normal_cs_sr_wr), \
        .latches_normal_latches_cs_eax_wr              (rr_latches_normal_cs_eax_wr), \
        .latches_normal_latches_cs_MOVS_OP             (rr_latches_normal_cs_MOVS_OP), \
        .latches_normal_latches_cs_datasize            (rr_latches_normal_cs_datasize), \
        .latches_normal_latches_cs_will_mod_zf         (rr_latches_normal_cs_will_mod_zf), \
        .latches_normal_latches_cs_seg_1_valid         (rr_latches_normal_cs_seg_1_valid), \
        .latches_normal_latches_cs_seg_0_id            (rr_latches_normal_cs_seg_0_id), \
        .latches_normal_latches_cs_seg_1_id            (rr_latches_normal_cs_seg_1_id), \
        .latches_normal_latches_cs_special_modrm_bs    (rr_latches_normal_cs_special_modrm_bs), \
        .latches_normal_latches_cs_special_br          (rr_latches_normal_cs_special_br), \
        .latches_normal_latches_dc_cs_LD_OP            (rr_latches_normal_dc_cs_LD_OP), \
        .latches_normal_latches_dc_cs_ST_OP            (rr_latches_normal_dc_cs_ST_OP), \
        .latches_normal_latches_dc_cs_dr_upper8        (rr_latches_normal_dc_cs_dr_upper8), \
        .latches_normal_latches_dc_cs_sr_upper8        (rr_latches_normal_dc_cs_sr_upper8), \
        .latches_normal_latches_dc_cs_datasize         (rr_latches_normal_dc_cs_datasize), \
        .latches_normal_latches_mem_cs_ST_OP           (rr_latches_normal_mem_cs_ST_OP), \
        .latches_normal_latches_mem_cs_LD_OP           (rr_latches_normal_mem_cs_LD_OP), \
        .latches_normal_latches_exe_cs_ST_OP           (rr_latches_normal_exe_cs_ST_OP), \
        .latches_normal_latches_exe_cs_OP_TYPE         (rr_latches_normal_exe_cs_OP_TYPE), \
        .latches_normal_latches_exe_cs_alu_inputA_sel  (rr_latches_normal_exe_cs_alu_inputA_sel), \
        .latches_normal_latches_exe_cs_alu_inputB_sel  (rr_latches_normal_exe_cs_alu_inputB_sel), \
        .latches_normal_latches_exe_cs_branch_target_sel(rr_latches_normal_exe_cs_branch_target_sel), \
        .latches_normal_latches_exe_cs_shift_by_one    (rr_latches_normal_exe_cs_shift_by_one), \
        .latches_normal_latches_exe_cs_br_ucond        (rr_latches_normal_exe_cs_br_ucond), \
        .latches_normal_latches_exe_cs_relative_branch (rr_latches_normal_exe_cs_relative_branch), \
        .latches_normal_latches_exe_cs_special_br      (rr_latches_normal_exe_cs_special_br), \
        .latches_normal_latches_exe_cs_is_far          (rr_latches_normal_exe_cs_is_far), \
        .latches_normal_latches_exe_cs_is_call         (rr_latches_normal_exe_cs_is_call), \
        .latches_normal_latches_exe_cs_second_flag_needed(rr_latches_normal_exe_cs_second_flag_needed), \
        .latches_normal_latches_exe_cs_rep_no_zf_update(rr_latches_normal_exe_cs_rep_no_zf_update), \
        .latches_normal_latches_wb_cs_ST_OP            (rr_latches_normal_wb_cs_ST_OP), \
        .latches_normal_latches_wb_cs_WB_DR            (rr_latches_normal_wb_cs_WB_DR), \
        .latches_normal_latches_wb_cs_WB_SR            (rr_latches_normal_wb_cs_WB_SR), \
        .latches_normal_latches_wb_cs_WB_EAX           (rr_latches_normal_wb_cs_WB_EAX), \
        .latches_normal_latches_br_info_valid          (rr_latches_normal_br_info_valid), \
        .latches_normal_latches_br_info_br_eip         (rr_latches_normal_br_info_br_eip), \
        .latches_normal_latches_br_info_br_xcl         (rr_latches_normal_br_info_br_xcl), \
        .latches_normal_latches_br_info_br_pred_taken  (rr_latches_normal_br_info_br_pred_taken), \
        .latches_normal_latches_br_info_speculative_target(rr_latches_normal_br_info_speculative_target), \
        .latches_normal_latches_NEIP                   (rr_latches_normal_NEIP), \
        .latches_normal_latches_EIP                    (rr_latches_normal_EIP), \
        .latches_normal_latches_EAX                    (rr_latches_normal_EAX), \
        .latches_normal_latches_imm64                  (rr_latches_normal_imm64), \
        .latches_normal_latches_sib_idx_id             (rr_latches_normal_sib_idx_id), \
        .latches_normal_latches_sib_base_id            (rr_latches_normal_sib_base_id), \
        .latches_normal_latches_sib_needed             (rr_latches_normal_sib_needed), \
        .latches_normal_latches_sib_scale              (rr_latches_normal_sib_scale), \
        .latches_normal_latches_disp_needed            (rr_latches_normal_disp_needed), \
        .latches_normal_latches_disp_size              (rr_latches_normal_disp_size), \
        .latches_normal_latches_displacement           (rr_latches_normal_displacement), \
        .latches_rep_latches_valid                  (rr_latches_rep_valid), \
        .latches_rep_latches_cs_ST_SEL              (rr_latches_rep_cs_ST_SEL), \
        .latches_rep_latches_cs_MODRM_NEEDED        (rr_latches_rep_cs_MODRM_NEEDED), \
        .latches_rep_latches_cs_RM_IS_DR            (rr_latches_rep_cs_RM_IS_DR), \
        .latches_rep_latches_cs_SWITCH_LD_ADDY      (rr_latches_rep_cs_SWITCH_LD_ADDY), \
        .latches_rep_latches_cs_LD_OP               (rr_latches_rep_cs_LD_OP), \
        .latches_rep_latches_cs_ST_OP               (rr_latches_rep_cs_ST_OP), \
        .latches_rep_latches_cs_dr_id               (rr_latches_rep_cs_dr_id), \
        .latches_rep_latches_cs_sr_id               (rr_latches_rep_cs_sr_id), \
        .latches_rep_latches_cs_dr_rd               (rr_latches_rep_cs_dr_rd), \
        .latches_rep_latches_cs_sr_rd               (rr_latches_rep_cs_sr_rd), \
        .latches_rep_latches_cs_eax_rd              (rr_latches_rep_cs_eax_rd), \
        .latches_rep_latches_cs_dr_wr               (rr_latches_rep_cs_dr_wr), \
        .latches_rep_latches_cs_sr_wr               (rr_latches_rep_cs_sr_wr), \
        .latches_rep_latches_cs_eax_wr              (rr_latches_rep_cs_eax_wr), \
        .latches_rep_latches_cs_MOVS_OP             (rr_latches_rep_cs_MOVS_OP), \
        .latches_rep_latches_cs_datasize            (rr_latches_rep_cs_datasize), \
        .latches_rep_latches_cs_will_mod_zf         (rr_latches_rep_cs_will_mod_zf), \
        .latches_rep_latches_cs_seg_1_valid         (rr_latches_rep_cs_seg_1_valid), \
        .latches_rep_latches_cs_seg_0_id            (rr_latches_rep_cs_seg_0_id), \
        .latches_rep_latches_cs_seg_1_id            (rr_latches_rep_cs_seg_1_id), \
        .latches_rep_latches_cs_special_modrm_bs    (rr_latches_rep_cs_special_modrm_bs), \
        .latches_rep_latches_cs_special_br          (rr_latches_rep_cs_special_br), \
        .latches_rep_latches_dc_cs_LD_OP            (rr_latches_rep_dc_cs_LD_OP), \
        .latches_rep_latches_dc_cs_ST_OP            (rr_latches_rep_dc_cs_ST_OP), \
        .latches_rep_latches_dc_cs_dr_upper8        (rr_latches_rep_dc_cs_dr_upper8), \
        .latches_rep_latches_dc_cs_sr_upper8        (rr_latches_rep_dc_cs_sr_upper8), \
        .latches_rep_latches_dc_cs_datasize         (rr_latches_rep_dc_cs_datasize), \
        .latches_rep_latches_mem_cs_ST_OP           (rr_latches_rep_mem_cs_ST_OP), \
        .latches_rep_latches_mem_cs_LD_OP           (rr_latches_rep_mem_cs_LD_OP), \
        .latches_rep_latches_exe_cs_ST_OP           (rr_latches_rep_exe_cs_ST_OP), \
        .latches_rep_latches_exe_cs_OP_TYPE         (rr_latches_rep_exe_cs_OP_TYPE), \
        .latches_rep_latches_exe_cs_alu_inputA_sel  (rr_latches_rep_exe_cs_alu_inputA_sel), \
        .latches_rep_latches_exe_cs_alu_inputB_sel  (rr_latches_rep_exe_cs_alu_inputB_sel), \
        .latches_rep_latches_exe_cs_branch_target_sel(rr_latches_rep_exe_cs_branch_target_sel), \
        .latches_rep_latches_exe_cs_shift_by_one    (rr_latches_rep_exe_cs_shift_by_one), \
        .latches_rep_latches_exe_cs_br_ucond        (rr_latches_rep_exe_cs_br_ucond), \
        .latches_rep_latches_exe_cs_relative_branch (rr_latches_rep_exe_cs_relative_branch), \
        .latches_rep_latches_exe_cs_special_br      (rr_latches_rep_exe_cs_special_br), \
        .latches_rep_latches_exe_cs_is_far          (rr_latches_rep_exe_cs_is_far), \
        .latches_rep_latches_exe_cs_is_call         (rr_latches_rep_exe_cs_is_call), \
        .latches_rep_latches_exe_cs_second_flag_needed(rr_latches_rep_exe_cs_second_flag_needed), \
        .latches_rep_latches_exe_cs_rep_no_zf_update(rr_latches_rep_exe_cs_rep_no_zf_update), \
        .latches_rep_latches_wb_cs_ST_OP            (rr_latches_rep_wb_cs_ST_OP), \
        .latches_rep_latches_wb_cs_WB_DR            (rr_latches_rep_wb_cs_WB_DR), \
        .latches_rep_latches_wb_cs_WB_SR            (rr_latches_rep_wb_cs_WB_SR), \
        .latches_rep_latches_wb_cs_WB_EAX           (rr_latches_rep_wb_cs_WB_EAX), \
        .latches_rep_latches_br_info_valid          (rr_latches_rep_br_info_valid), \
        .latches_rep_latches_br_info_br_eip         (rr_latches_rep_br_info_br_eip), \
        .latches_rep_latches_br_info_br_xcl         (rr_latches_rep_br_info_br_xcl), \
        .latches_rep_latches_br_info_br_pred_taken  (rr_latches_rep_br_info_br_pred_taken), \
        .latches_rep_latches_br_info_speculative_target(rr_latches_rep_br_info_speculative_target), \
        .latches_rep_latches_NEIP                   (rr_latches_rep_NEIP), \
        .latches_rep_latches_EIP                    (rr_latches_rep_EIP), \
        .latches_rep_latches_EAX                    (rr_latches_rep_EAX), \
        .latches_rep_latches_imm64                  (rr_latches_rep_imm64), \
        .latches_rep_latches_sib_idx_id             (rr_latches_rep_sib_idx_id), \
        .latches_rep_latches_sib_base_id            (rr_latches_rep_sib_base_id), \
        .latches_rep_latches_sib_needed             (rr_latches_rep_sib_needed), \
        .latches_rep_latches_sib_scale              (rr_latches_rep_sib_scale), \
        .latches_rep_latches_disp_needed            (rr_latches_rep_disp_needed), \
        .latches_rep_latches_disp_size              (rr_latches_rep_disp_size), \
        .latches_rep_latches_displacement           (rr_latches_rep_displacement), \
        .fetch_outs_exp_pipe_clear (fetch_outputs_exp_pipe_clear), \
        .decode_outs_rep_latch (decode_outputs_rep_latch), \
        .decode_outs_decode_gp (decode_outputs_decode_gp), \
        .dc_outs_valid (dc_outputs_valid), \
        .dc_outs_stall (dc_outputs_stall), \
        .mem_outs_valid (mem_outputs_valid), \
        .mem_outs_stall (mem_outputs_stall), \
        .exe_outs_valid           (exe_outputs_valid), \
        .exe_outs_br_res_flush    (exe_outputs_br_res_flush_rr), \
        .exe_outs_br_res_farFlush (exe_outputs_br_res_farFlush), \
        .exe_outs_br_res_callFlush(exe_outputs_br_res_callFlush), \
        .exe_outs_DR_0_we         (exe_outputs_DR_0_we), \
        .exe_outs_DR_0_id         (exe_outputs_DR_0_id), \
        .exe_outs_DR_0_data       (exe_outputs_DR_0_data), \
        .exe_outs_DR_1_we         (exe_outputs_DR_1_we), \
        .exe_outs_DR_1_id         (exe_outputs_DR_1_id), \
        .exe_outs_DR_1_data       (exe_outputs_DR_1_data), \
        .wb_outs_wb_stall (wb_outputs_wb_stall), \
        .dc_latches_next_valid                       (dc_latches_next_valid), \
        .dc_latches_next_cs_LD_OP                    (dc_latches_next_cs_LD_OP), \
        .dc_latches_next_cs_ST_OP                    (dc_latches_next_cs_ST_OP), \
        .dc_latches_next_cs_dr_upper8                (dc_latches_next_cs_dr_upper8), \
        .dc_latches_next_cs_sr_upper8                (dc_latches_next_cs_sr_upper8), \
        .dc_latches_next_cs_datasize                 (dc_latches_next_cs_datasize), \
        .dc_latches_next_mem_cs_ST_OP                (dc_latches_next_mem_cs_ST_OP), \
        .dc_latches_next_mem_cs_LD_OP                (dc_latches_next_mem_cs_LD_OP), \
        .dc_latches_next_exe_cs_ST_OP                (dc_latches_next_exe_cs_ST_OP), \
        .dc_latches_next_exe_cs_OP_TYPE              (dc_latches_next_exe_cs_OP_TYPE), \
        .dc_latches_next_exe_cs_alu_inputA_sel       (dc_latches_next_exe_cs_alu_inputA_sel), \
        .dc_latches_next_exe_cs_alu_inputB_sel       (dc_latches_next_exe_cs_alu_inputB_sel), \
        .dc_latches_next_exe_cs_branch_target_sel    (dc_latches_next_exe_cs_branch_target_sel), \
        .dc_latches_next_exe_cs_shift_by_one         (dc_latches_next_exe_cs_shift_by_one), \
        .dc_latches_next_exe_cs_br_ucond             (dc_latches_next_exe_cs_br_ucond), \
        .dc_latches_next_exe_cs_relative_branch      (dc_latches_next_exe_cs_relative_branch), \
        .dc_latches_next_exe_cs_special_br           (dc_latches_next_exe_cs_special_br), \
        .dc_latches_next_exe_cs_is_far               (dc_latches_next_exe_cs_is_far), \
        .dc_latches_next_exe_cs_is_call              (dc_latches_next_exe_cs_is_call), \
        .dc_latches_next_exe_cs_second_flag_needed   (dc_latches_next_exe_cs_second_flag_needed), \
        .dc_latches_next_exe_cs_rep_no_zf_update     (dc_latches_next_exe_cs_rep_no_zf_update), \
        .dc_latches_next_wb_cs_ST_OP                 (dc_latches_next_wb_cs_ST_OP), \
        .dc_latches_next_wb_cs_WB_DR                 (dc_latches_next_wb_cs_WB_DR), \
        .dc_latches_next_wb_cs_WB_SR                 (dc_latches_next_wb_cs_WB_SR), \
        .dc_latches_next_wb_cs_WB_EAX                (dc_latches_next_wb_cs_WB_EAX), \
        .dc_latches_next_br_info_valid               (dc_latches_next_br_info_valid), \
        .dc_latches_next_br_info_br_eip              (dc_latches_next_br_info_br_eip), \
        .dc_latches_next_br_info_br_xcl              (dc_latches_next_br_info_br_xcl), \
        .dc_latches_next_br_info_br_pred_taken       (dc_latches_next_br_info_br_pred_taken), \
        .dc_latches_next_br_info_speculative_target  (dc_latches_next_br_info_speculative_target), \
        .dc_latches_next_rr_gp                       (dc_latches_next_rr_gp), \
        .dc_latches_next_ld_vaddy                    (_dc_latches_next_ld_vaddy_), \
        .dc_latches_next_seg0_limit_w_datasize       (dc_latches_next_seg0_limit_w_datasize), \
        .dc_latches_next_seg0_limit_wo_datasize      (dc_latches_next_seg0_limit_wo_datasize), \
        .dc_latches_next_next_ld_vaddy               (dc_latches_next_next_ld_vaddy), \
        .dc_latches_next_ld_laddy                    (dc_latches_next_ld_laddy), \
        .dc_latches_next_ld_stack_access             (dc_latches_next_ld_stack_access), \
        .dc_latches_next_st_vaddy                    (_dc_latches_next_st_vaddy_), \
        .dc_latches_next_seg1_limit_w_datasize       (dc_latches_next_seg1_limit_w_datasize), \
        .dc_latches_next_seg1_limit_wo_datasize      (dc_latches_next_seg1_limit_wo_datasize), \
        .dc_latches_next_next_st_vaddy               (dc_latches_next_next_st_vaddy), \
        .dc_latches_next_st_laddy                    (dc_latches_next_st_laddy), \
        .dc_latches_next_st_stack_access             (dc_latches_next_st_stack_access), \
        .dc_latches_next_NEIP                        (dc_latches_next_NEIP), \
        .dc_latches_next_EIP                         (dc_latches_next_EIP), \
        .dc_latches_next_EAX                         (dc_latches_next_EAX), \
        .dc_latches_next_imm64                       (dc_latches_next_imm64), \
        .dc_latches_next_sr_id                       (dc_latches_next_sr_id), \
        .dc_latches_next_sr_data                     (dc_latches_next_sr_data), \
        .dc_latches_next_dr_id                       (dc_latches_next_dr_id), \
        .dc_latches_next_dr_data                     (dc_latches_next_dr_data), \
        .dc_latches_next_cs_datasize_0               (dc_latches_next_cs_datasize_0), \
        .dc_latches_next_cs_datasize_1               (dc_latches_next_cs_datasize_1), \
        .dc_latches_next_cs_datasize_2               (dc_latches_next_cs_datasize_2), \
        .dc_latches_next_cs_LD_OP_0                  (dc_latches_next_cs_LD_OP_0), \
        .dc_latches_next_cs_LD_OP_1                  (dc_latches_next_cs_LD_OP_1), \
        .dc_latches_next_cs_LD_OP_2                  (dc_latches_next_cs_LD_OP_2), \
        .dc_latches_next_cs_LD_OP_3                  (dc_latches_next_cs_LD_OP_3), \
        .dc_latches_next_cs_ST_OP_0                  (dc_latches_next_cs_ST_OP_0), \
        .dc_latches_next_valid_0                     (dc_latches_next_valid_0), \
        .dc_latches_next_valid_1                     (dc_latches_next_valid_1), \
        .dc_latches_next_valid_2                     (dc_latches_next_valid_2), \
        .outs_valid             (rr_outputs_valid), \
        .outs_stall             (rr_outputs_stall), \
        .outs_ecx_sb            (rr_outputs_ecx_sb), \
        .outs_ecx               (rr_outputs_ecx), \
        .outs_eax               (rr_outputs_eax), \
        .outs_set_ZF_sb         (rr_outputs_set_ZF_sb), \
        .outs_codeSeg_sb        (rr_outputs_codeSeg_sb), \
        .outs_codeSeg_data      (rr_outputs_codeSeg_data), \
        .outs_codeSeg_limit     (rr_outputs_codeSeg_limit), \
        .outs_dc_stage_latch_we (rr_outputs_dc_stage_latch_we), \
        .outs_regFileValues_0  (rr_outputs_regFileValues_0), \
        .outs_regFileValues_1  (rr_outputs_regFileValues_1), \
        .outs_regFileValues_2  (rr_outputs_regFileValues_2), \
        .outs_regFileValues_3  (rr_outputs_regFileValues_3), \
        .outs_regFileValues_4  (rr_outputs_regFileValues_4), \
        .outs_regFileValues_5  (rr_outputs_regFileValues_5), \
        .outs_regFileValues_6  (rr_outputs_regFileValues_6), \
        .outs_regFileValues_7  (rr_outputs_regFileValues_7), \
        .outs_regFileValues_8  (rr_outputs_regFileValues_8), \
        .outs_regFileValues_9  (rr_outputs_regFileValues_9), \
        .outs_regFileValues_10 (rr_outputs_regFileValues_10), \
        .outs_regFileValues_11 (rr_outputs_regFileValues_11), \
        .outs_regFileValues_12 (rr_outputs_regFileValues_12), \
        .outs_regFileValues_13 (rr_outputs_regFileValues_13), \
        .outs_regFileValues_14 (rr_outputs_regFileValues_14), \
        .outs_regFileValues_15 (rr_outputs_regFileValues_15), \
        .outs_regFileValues_16 (rr_outputs_regFileValues_16), \
        .outs_regFileValues_17 (rr_outputs_regFileValues_17), \
        .outs_regFileValues_18 (rr_outputs_regFileValues_18), \
        .outs_regFileValues_19 (rr_outputs_regFileValues_19), \
        .outs_regFileValues_20 (rr_outputs_regFileValues_20), \
        .outs_regFileValues_21 (rr_outputs_regFileValues_21), \
        .outs_regFileValues_22 (rr_outputs_regFileValues_22), \
        .outs_regFileValues_23 (rr_outputs_regFileValues_23), \
        .outs_regFileValues_24 (rr_outputs_regFileValues_24), \
        .outs_regFileValues_25 (rr_outputs_regFileValues_25) \
    );
