#!/usr/bin/env python3
"""
Core Register Loader RTL Generation Script
Reads a JSON config and emits pure Verilog-2005 structural stimulus
to populate EIP, SPC, IDTR, and segment limit registers via
hierarchical path force/non-blocking assignments.

Usage:
    python3 gen_reg.py  <config.json>
"""

import json
import os
import re
import argparse


# --------------------------------------------------------------------------- #
#  Shared helpers  (same as gen_tlb.py)
# --------------------------------------------------------------------------- #

TICK = "__VERILOG_TICK__"


def load_config(path: str) -> dict:
    with open(path) as f:
        raw = f.read()

    # Escape bare apostrophes inside JSON string values so the parser
    # doesn't choke on Verilog literals like  20'h12345
    def escape_ticks(text: str) -> str:
        result, in_str = [], False
        i = 0
        while i < len(text):
            c = text[i]
            # Handle escaped quote inside string
            if c == '\\' and in_str and i + 1 < len(text) and text[i+1] == '"':
                result.append(c)
                result.append(text[i+1])
                i += 2
                continue
            if c == '"':
                in_str = not in_str
                result.append(c)
            elif c == "'" and in_str:
                result.append(TICK)
            else:
                result.append(c)
            i += 1
        return "".join(result)

    raw = escape_ticks(raw)

    # Remove trailing commas before } or ]
    raw = re.sub(r",\s*([}\]])", r"\1", raw)

    # Add missing commas between adjacent entries  }  \n  "key"
    # (handles the user's format where commas are omitted between top-level blocks)
    raw = re.sub(r'(})\s*\n(\s*")', r'\1,\n\2', raw)

    cfg = json.loads(raw)

    # Restore ticks in all string values recursively
    def restore_ticks(obj):
        if isinstance(obj, dict):
            return {k: restore_ticks(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [restore_ticks(v) for v in obj]
        if isinstance(obj, str):
            return obj.replace(TICK, "'")
        return obj

    return restore_ticks(cfg)


def parse_verilog_literal(literal: str) -> tuple[int, int, str]:
    """
    Parse a Verilog literal.  Tolerates both  32'h...  and  32h'...  typos.
    Returns (width, int_value, base_char).
    """
    s = literal.strip().replace("_", "")

    # Normalise the common typo  32h'XXXX  →  32'hXXXX
    s = re.sub(r"^(\d+)([bBoOdDhH])'", r"\1'\2", s)

    m = re.fullmatch(r"(\d+)'([bBoOdDhH])([0-9a-fA-FxXzZ]+)", s)
    if not m:
        raise ValueError(f"Cannot parse Verilog literal: '{literal}'")

    width  = int(m.group(1))
    base   = m.group(2).lower()
    digits = m.group(3)
    bases  = {"b": 2, "o": 8, "d": 10, "h": 16}
    value  = int(digits, bases[base])
    return width, value, base


def format_literal(width: int, value: int, base: str = "h") -> str:
    if base == "h":
        hex_digits = (width + 3) // 4
        return f"{width}'h{value:0{hex_digits}X}"
    elif base == "b":
        return f"{width}'b{value:0{width}b}"
    else:
        return f"{width}'d{value}"


def should_load(block: dict) -> bool:
    return str(block.get("load", "false")).strip().lower() in ("true", "1", "yes")


# --------------------------------------------------------------------------- #
#  Verilog generation
# --------------------------------------------------------------------------- #

I  = "        "   # 8-space indent (inside initial begin)
I2 = "    "       # 4-space indent (module body)

SEG_REGS = ("CS", "DS", "SS", "ES", "FS", "GS")


def scalar_assignment(path: str, val_str: str) -> str:
    """Single  path <= literal;  line."""
    w, v, b = parse_verilog_literal(val_str)
    return f"{I}{path} = {format_literal(w, v, b)};"


def generate_verilog(cfg: dict) -> str:
    module_name = cfg.get("Module Name", "coreRegLoader").strip() or "coreRegLoader"
    startup_ns  = cfg.get("startUpDelay", "30")

    lines = []
    lines.append(f"// Auto-generated by gen_reg.py")
    lines.append(f"// Core register loader : {module_name}")
    lines.append("")
    lines.append(f"module {module_name} ();")
    lines.append("")
    lines.append(f"{I2}initial begin")
    lines.append(f"{I}// Wait for design to come out of reset")
    lines.append(f"{I}#{startup_ns};")
    lines.append("")

    # ------------------------------------------------------------------ #
    #  Scalar registers  EIP / SPC / IDTR
    # ------------------------------------------------------------------ #
    for reg in ("EIP", "SPC", "IDTR"):
        blk = cfg.get(reg)
        if blk is None:
            continue
        if not should_load(blk):
            lines.append(f"{I}// {reg} : load=false  (skipped)")
            lines.append("")
            continue

        path = blk.get("path", "").strip()
        val  = blk.get("val",  "").strip()

        if not path:
            raise ValueError(f"{reg}: 'path' is required when load=true")
        if not val:
            raise ValueError(f"{reg}: 'val' is required when load=true")

        lines.append(f"{I}// ---- {reg} ----")
        lines.append(scalar_assignment(path, val))
        lines.append("")

    # ------------------------------------------------------------------ #
    #  Segment limit block
    # ------------------------------------------------------------------ #
    seg_blk = cfg.get("SegLimitVals")
    if seg_blk is not None:
        if not should_load(seg_blk):
            lines.append(f"{I}// SegLimitVals : load=false  (skipped)")
            lines.append("")
        else:
            lines.append(f"{I}// ---- Segment Limits ----")
            for seg in SEG_REGS:
                entry = seg_blk.get(seg)
                if entry is None:
                    lines.append(f"{I}// {seg} : not present in config (skipped)")
                    continue

                # entry is [val_literal, hierarchical_path]
                if not isinstance(entry, list) or len(entry) < 2:
                    raise ValueError(
                        f"SegLimitVals.{seg} must be [val_literal, path], got: {entry!r}"
                    )
                val_str = entry[0].strip()
                path    = entry[1].strip()

                lines.append(f"{I}// {seg}")
                lines.append(scalar_assignment(path, val_str))
            lines.append("")

    # ------------------------------------------------------------------ #
    lines.append(f"{I2}end  // initial")
    lines.append("")
    lines.append(f"endmodule : {module_name}")
    lines.append("")

    return "\n".join(lines)


# --------------------------------------------------------------------------- #
#  Main
# --------------------------------------------------------------------------- #

def main():
    ap = argparse.ArgumentParser(
        description="Generate core-register-population Verilog from JSON config."
    )
    ap.add_argument("config", help="Path to the JSON configuration file")
    args = ap.parse_args()

    cfg = load_config(args.config)

    verilog = generate_verilog(cfg)

    out_dir = cfg.get("outputPath", "gen/").rstrip("/")
    os.makedirs(out_dir, exist_ok=True)

    module_name = cfg.get("Module Name", "coreRegLoader").strip() or "coreRegLoader"
    out_path = os.path.join(out_dir, f"{module_name}.sv")

    with open(out_path, "w") as f:
        f.write(verilog)

    print(f"[gen_reg] Written → {out_path}")
    #print(verilog)


if __name__ == "__main__":
    main()
