module tb_rr_fanout

module RR (
    .clk(clk_i),
    .rst(rst_i),
    .latches_normal_latches_valid(latches_normal_latches_valid_i),
    .latches_normal_latches_cs_ST_SEL(latches_normal_latches_cs_ST_SEL_i),
    .latches_normal_latches_cs_MODRM_NEEDED(latches_normal_latches_cs_MODRM_NEEDED_i),
    .latches_normal_latches_cs_RM_IS_DR(latches_normal_latches_cs_RM_IS_DR_i),
    .latches_normal_latches_cs_SWITCH_LD_ADDY(latches_normal_latches_cs_SWITCH_LD_ADDY_i),
    .latches_normal_latches_cs_LD_OP(latches_normal_latches_cs_LD_OP_i),
    .latches_normal_latches_cs_ST_OP(latches_normal_latches_cs_ST_OP_i),
    .latches_normal_latches_cs_dr_id(latches_normal_latches_cs_dr_id_i),
    .latches_normal_latches_cs_sr_id(latches_normal_latches_cs_sr_id_i),
    .latches_normal_latches_cs_dr_rd(latches_normal_latches_cs_dr_rd_i),
    .latches_normal_latches_cs_sr_rd(latches_normal_latches_cs_sr_rd_i),
    .latches_normal_latches_cs_eax_rd(latches_normal_latches_cs_eax_rd_i),
    .latches_normal_latches_cs_dr_wr(latches_normal_latches_cs_dr_wr_i),
    .latches_normal_latches_cs_sr_wr(latches_normal_latches_cs_sr_wr_i),
    .latches_normal_latches_cs_eax_wr(latches_normal_latches_cs_eax_wr_i),
    .latches_normal_latches_cs_MOVS_OP(latches_normal_latches_cs_MOVS_OP_i),
    .latches_normal_latches_cs_datasize(latches_normal_latches_cs_datasize_i),
    .latches_normal_latches_cs_will_mod_zf(latches_normal_latches_cs_will_mod_zf_i),
    .latches_normal_latches_cs_seg_1_valid(latches_normal_latches_cs_seg_1_valid_i),
    .latches_normal_latches_cs_seg_0_id(latches_normal_latches_cs_seg_0_id_i),
    .latches_normal_latches_cs_seg_1_id(latches_normal_latches_cs_seg_1_id_i),
    .latches_normal_latches_cs_special_modrm_bs(latches_normal_latches_cs_special_modrm_bs_i),
    .latches_normal_latches_cs_special_br(latches_normal_latches_cs_special_br_i),
    .latches_normal_latches_dc_cs_LD_OP(latches_normal_latches_dc_cs_LD_OP_i),
    .latches_normal_latches_dc_cs_ST_OP(latches_normal_latches_dc_cs_ST_OP_i),
    .latches_normal_latches_dc_cs_dr_upper8(latches_normal_latches_dc_cs_dr_upper8_i),
    .latches_normal_latches_dc_cs_sr_upper8(latches_normal_latches_dc_cs_sr_upper8_i),
    .latches_normal_latches_dc_cs_datasize(latches_normal_latches_dc_cs_datasize_i),
    .latches_normal_latches_mem_cs_ST_OP(latches_normal_latches_mem_cs_ST_OP_i),
    .latches_normal_latches_mem_cs_LD_OP(latches_normal_latches_mem_cs_LD_OP_i),
    .latches_normal_latches_exe_cs_ST_OP(latches_normal_latches_exe_cs_ST_OP_i),
    .latches_normal_latches_exe_cs_OP_TYPE(latches_normal_latches_exe_cs_OP_TYPE_i),
    .latches_normal_latches_exe_cs_alu_inputA_sel(latches_normal_latches_exe_cs_alu_inputA_sel_i),
    .latches_normal_latches_exe_cs_alu_inputB_sel(latches_normal_latches_exe_cs_alu_inputB_sel_i),
    .latches_normal_latches_exe_cs_branch_target_sel(latches_normal_latches_exe_cs_branch_target_sel_i),
    .latches_normal_latches_exe_cs_shift_by_one(latches_normal_latches_exe_cs_shift_by_one_i),
    .latches_normal_latches_exe_cs_br_ucond(latches_normal_latches_exe_cs_br_ucond_i),
    .latches_normal_latches_exe_cs_relative_branch(latches_normal_latches_exe_cs_relative_branch_i),
    .latches_normal_latches_exe_cs_special_br(latches_normal_latches_exe_cs_special_br_i),
    .latches_normal_latches_exe_cs_is_far(latches_normal_latches_exe_cs_is_far_i),
    .latches_normal_latches_exe_cs_is_call(latches_normal_latches_exe_cs_is_call_i),
    .latches_normal_latches_exe_cs_second_flag_needed(latches_normal_latches_exe_cs_second_flag_needed_i),
    .latches_normal_latches_exe_cs_rep_no_zf_update(latches_normal_latches_exe_cs_rep_no_zf_update_i),
    .latches_normal_latches_wb_cs_ST_OP(latches_normal_latches_wb_cs_ST_OP_i),
    .latches_normal_latches_wb_cs_WB_DR(latches_normal_latches_wb_cs_WB_DR_i),
    .latches_normal_latches_wb_cs_WB_SR(latches_normal_latches_wb_cs_WB_SR_i),
    .latches_normal_latches_wb_cs_WB_EAX(latches_normal_latches_wb_cs_WB_EAX_i),
    .latches_normal_latches_br_info_valid(latches_normal_latches_br_info_valid_i),
    .latches_normal_latches_br_info_br_eip(latches_normal_latches_br_info_br_eip_i),
    .latches_normal_latches_br_info_br_xcl(latches_normal_latches_br_info_br_xcl_i),
    .latches_normal_latches_br_info_br_pred_taken(latches_normal_latches_br_info_br_pred_taken_i),
    .latches_normal_latches_br_info_speculative_target(latches_normal_latches_br_info_speculative_target_i),
    .latches_normal_latches_NEIP(latches_normal_latches_NEIP_i),
    .latches_normal_latches_EIP(latches_normal_latches_EIP_i),
    .latches_normal_latches_EAX(latches_normal_latches_EAX_i),
    .latches_normal_latches_imm64(latches_normal_latches_imm64_i),
    .latches_normal_latches_sib_idx_id(latches_normal_latches_sib_idx_id_i),
    .latches_normal_latches_sib_base_id(latches_normal_latches_sib_base_id_i),
    .latches_normal_latches_sib_needed(latches_normal_latches_sib_needed_i),
    .latches_normal_latches_sib_scale(latches_normal_latches_sib_scale_i),
    .latches_normal_latches_disp_needed(latches_normal_latches_disp_needed_i),
    .latches_normal_latches_disp_size(latches_normal_latches_disp_size_i),
    .latches_normal_latches_displacement(latches_normal_latches_displacement_i),
    .latches_rep_latches_valid(latches_rep_latches_valid_i),
    .latches_rep_latches_cs_ST_SEL(latches_rep_latches_cs_ST_SEL_i),
    .latches_rep_latches_cs_MODRM_NEEDED(latches_rep_latches_cs_MODRM_NEEDED_i),
    .latches_rep_latches_cs_RM_IS_DR(latches_rep_latches_cs_RM_IS_DR_i),
    .latches_rep_latches_cs_SWITCH_LD_ADDY(latches_rep_latches_cs_SWITCH_LD_ADDY_i),
    .latches_rep_latches_cs_LD_OP(latches_rep_latches_cs_LD_OP_i),
    .latches_rep_latches_cs_ST_OP(latches_rep_latches_cs_ST_OP_i),
    .latches_rep_latches_cs_dr_id(latches_rep_latches_cs_dr_id_i),
    .latches_rep_latches_cs_sr_id(latches_rep_latches_cs_sr_id_i),
    .latches_rep_latches_cs_dr_rd(latches_rep_latches_cs_dr_rd_i),
    .latches_rep_latches_cs_sr_rd(latches_rep_latches_cs_sr_rd_i),
    .latches_rep_latches_cs_eax_rd(latches_rep_latches_cs_eax_rd_i),
    .latches_rep_latches_cs_dr_wr(latches_rep_latches_cs_dr_wr_i),
    .latches_rep_latches_cs_sr_wr(latches_rep_latches_cs_sr_wr_i),
    .latches_rep_latches_cs_eax_wr(latches_rep_latches_cs_eax_wr_i),
    .latches_rep_latches_cs_MOVS_OP(latches_rep_latches_cs_MOVS_OP_i),
    .latches_rep_latches_cs_datasize(latches_rep_latches_cs_datasize_i),
    .latches_rep_latches_cs_will_mod_zf(latches_rep_latches_cs_will_mod_zf_i),
    .latches_rep_latches_cs_seg_1_valid(latches_rep_latches_cs_seg_1_valid_i),
    .latches_rep_latches_cs_seg_0_id(latches_rep_latches_cs_seg_0_id_i),
    .latches_rep_latches_cs_seg_1_id(latches_rep_latches_cs_seg_1_id_i),
    .latches_rep_latches_cs_special_modrm_bs(latches_rep_latches_cs_special_modrm_bs_i),
    .latches_rep_latches_cs_special_br(latches_rep_latches_cs_special_br_i),
    .latches_rep_latches_dc_cs_LD_OP(latches_rep_latches_dc_cs_LD_OP_i),
    .latches_rep_latches_dc_cs_ST_OP(latches_rep_latches_dc_cs_ST_OP_i),
    .latches_rep_latches_dc_cs_dr_upper8(latches_rep_latches_dc_cs_dr_upper8_i),
    .latches_rep_latches_dc_cs_sr_upper8(latches_rep_latches_dc_cs_sr_upper8_i),
    .latches_rep_latches_dc_cs_datasize(latches_rep_latches_dc_cs_datasize_i),
    .latches_rep_latches_mem_cs_ST_OP(latches_rep_latches_mem_cs_ST_OP_i),
    .latches_rep_latches_mem_cs_LD_OP(latches_rep_latches_mem_cs_LD_OP_i),
    .latches_rep_latches_exe_cs_ST_OP(latches_rep_latches_exe_cs_ST_OP_i),
    .latches_rep_latches_exe_cs_OP_TYPE(latches_rep_latches_exe_cs_OP_TYPE_i),
    .latches_rep_latches_exe_cs_alu_inputA_sel(latches_rep_latches_exe_cs_alu_inputA_sel_i),
    .latches_rep_latches_exe_cs_alu_inputB_sel(latches_rep_latches_exe_cs_alu_inputB_sel_i),
    .latches_rep_latches_exe_cs_branch_target_sel(latches_rep_latches_exe_cs_branch_target_sel_i),
    .latches_rep_latches_exe_cs_shift_by_one(latches_rep_latches_exe_cs_shift_by_one_i),
    .latches_rep_latches_exe_cs_br_ucond(latches_rep_latches_exe_cs_br_ucond_i),
    .latches_rep_latches_exe_cs_relative_branch(latches_rep_latches_exe_cs_relative_branch_i),
    .latches_rep_latches_exe_cs_special_br(latches_rep_latches_exe_cs_special_br_i),
    .latches_rep_latches_exe_cs_is_far(latches_rep_latches_exe_cs_is_far_i),
    .latches_rep_latches_exe_cs_is_call(latches_rep_latches_exe_cs_is_call_i),
    .latches_rep_latches_exe_cs_second_flag_needed(latches_rep_latches_exe_cs_second_flag_needed_i),
    .latches_rep_latches_exe_cs_rep_no_zf_update(latches_rep_latches_exe_cs_rep_no_zf_update_i),
    .latches_rep_latches_wb_cs_ST_OP(latches_rep_latches_wb_cs_ST_OP_i),
    .latches_rep_latches_wb_cs_WB_DR(latches_rep_latches_wb_cs_WB_DR_i),
    .latches_rep_latches_wb_cs_WB_SR(latches_rep_latches_wb_cs_WB_SR_i),
    .latches_rep_latches_wb_cs_WB_EAX(latches_rep_latches_wb_cs_WB_EAX_i),
    .latches_rep_latches_br_info_valid(latches_rep_latches_br_info_valid_i),
    .latches_rep_latches_br_info_br_eip(latches_rep_latches_br_info_br_eip_i),
    .latches_rep_latches_br_info_br_xcl(latches_rep_latches_br_info_br_xcl_i),
    .latches_rep_latches_br_info_br_pred_taken(latches_rep_latches_br_info_br_pred_taken_i),
    .latches_rep_latches_br_info_speculative_target(latches_rep_latches_br_info_speculative_target_i),
    .latches_rep_latches_NEIP(latches_rep_latches_NEIP_i),
    .latches_rep_latches_EIP(latches_rep_latches_EIP_i),
    .latches_rep_latches_EAX(latches_rep_latches_EAX_i),
    .latches_rep_latches_imm64(latches_rep_latches_imm64_i),
    .latches_rep_latches_sib_idx_id(latches_rep_latches_sib_idx_id_i),
    .latches_rep_latches_sib_base_id(latches_rep_latches_sib_base_id_i),
    .latches_rep_latches_sib_needed(latches_rep_latches_sib_needed_i),
    .latches_rep_latches_sib_scale(latches_rep_latches_sib_scale_i),
    .latches_rep_latches_disp_needed(latches_rep_latches_disp_needed_i),
    .latches_rep_latches_disp_size(latches_rep_latches_disp_size_i),
    .latches_rep_latches_displacement(latches_rep_latches_displacement_i),
    .fetch_outs_exp_pipe_clear(fetch_outs_exp_pipe_clear_i),
    .decode_outs_rep_latch(decode_outs_rep_latch_i),
    .decode_outs_decode_gp(decode_outs_decode_gp_i),
    .dc_outs_valid(dc_outs_valid_i),
    .dc_outs_stall(dc_outs_stall_i),
    .mem_outs_valid(mem_outs_valid_i),
    .mem_outs_stall(mem_outs_stall_i),
    .exe_outs_valid(exe_outs_valid_i),
    .exe_outs_br_res_flush(exe_outs_br_res_flush_i),
    .exe_outs_br_res_farFlush(exe_outs_br_res_farFlush_i),
    .exe_outs_br_res_callFlush(exe_outs_br_res_callFlush_i),
    .exe_outs_DR_0_we(exe_outs_DR_0_we_i),
    .exe_outs_DR_0_id(exe_outs_DR_0_id_i),
    .exe_outs_DR_0_data(exe_outs_DR_0_data_i),
    .exe_outs_DR_1_we(exe_outs_DR_1_we_i),
    .exe_outs_DR_1_id(exe_outs_DR_1_id_i),
    .exe_outs_DR_1_data(exe_outs_DR_1_data_i),
    .wb_outs_wb_stall(wb_outs_wb_stall_i),
    .dc_latches_next_valid(dc_latches_next_valid_i),
    .dc_latches_next_cs_LD_OP(dc_latches_next_cs_LD_OP_i),
    .dc_latches_next_cs_ST_OP(dc_latches_next_cs_ST_OP_i),
    .dc_latches_next_cs_dr_upper8(dc_latches_next_cs_dr_upper8_i),
    .dc_latches_next_cs_sr_upper8(dc_latches_next_cs_sr_upper8_i),
    .dc_latches_next_cs_datasize(dc_latches_next_cs_datasize_i),
    .dc_latches_next_mem_cs_ST_OP(dc_latches_next_mem_cs_ST_OP_i),
    .dc_latches_next_mem_cs_LD_OP(dc_latches_next_mem_cs_LD_OP_i),
    .dc_latches_next_exe_cs_ST_OP(dc_latches_next_exe_cs_ST_OP_i),
    .dc_latches_next_exe_cs_OP_TYPE(dc_latches_next_exe_cs_OP_TYPE_i),
    .dc_latches_next_exe_cs_alu_inputA_sel(dc_latches_next_exe_cs_alu_inputA_sel_i),
    .dc_latches_next_exe_cs_alu_inputB_sel(dc_latches_next_exe_cs_alu_inputB_sel_i),
    .dc_latches_next_exe_cs_branch_target_sel(dc_latches_next_exe_cs_branch_target_sel_i),
    .dc_latches_next_exe_cs_shift_by_one(dc_latches_next_exe_cs_shift_by_one_i),
    .dc_latches_next_exe_cs_br_ucond(dc_latches_next_exe_cs_br_ucond_i),
    .dc_latches_next_exe_cs_relative_branch(dc_latches_next_exe_cs_relative_branch_i),
    .dc_latches_next_exe_cs_special_br(dc_latches_next_exe_cs_special_br_i),
    .dc_latches_next_exe_cs_is_far(dc_latches_next_exe_cs_is_far_i),
    .dc_latches_next_exe_cs_is_call(dc_latches_next_exe_cs_is_call_i),
    .dc_latches_next_exe_cs_second_flag_needed(dc_latches_next_exe_cs_second_flag_needed_i),
    .dc_latches_next_exe_cs_rep_no_zf_update(dc_latches_next_exe_cs_rep_no_zf_update_i),
    .dc_latches_next_wb_cs_ST_OP(dc_latches_next_wb_cs_ST_OP_i),
    .dc_latches_next_wb_cs_WB_DR(dc_latches_next_wb_cs_WB_DR_i),
    .dc_latches_next_wb_cs_WB_SR(dc_latches_next_wb_cs_WB_SR_i),
    .dc_latches_next_wb_cs_WB_EAX(dc_latches_next_wb_cs_WB_EAX_i),
    .dc_latches_next_br_info_valid(dc_latches_next_br_info_valid_i),
    .dc_latches_next_br_info_br_eip(dc_latches_next_br_info_br_eip_i),
    .dc_latches_next_br_info_br_xcl(dc_latches_next_br_info_br_xcl_i),
    .dc_latches_next_br_info_br_pred_taken(dc_latches_next_br_info_br_pred_taken_i),
    .dc_latches_next_br_info_speculative_target(dc_latches_next_br_info_speculative_target_i),
    .dc_latches_next_rr_gp(dc_latches_next_rr_gp_i),
    .dc_latches_next_ld_vaddy(dc_latches_next_ld_vaddy_i),
    .dc_latches_next_seg0_limit_w_datasize(dc_latches_next_seg0_limit_w_datasize_i),
    .dc_latches_next_seg0_limit_wo_datasize(dc_latches_next_seg0_limit_wo_datasize_i),
    .dc_latches_next_next_ld_vaddy(dc_latches_next_next_ld_vaddy_i),
    .dc_latches_next_ld_laddy(dc_latches_next_ld_laddy_i),
    .dc_latches_next_ld_stack_access(dc_latches_next_ld_stack_access_i),
    .dc_latches_next_st_vaddy(dc_latches_next_st_vaddy_i),
    .dc_latches_next_seg1_limit_w_datasize(dc_latches_next_seg1_limit_w_datasize_i),
    .dc_latches_next_seg1_limit_wo_datasize(dc_latches_next_seg1_limit_wo_datasize_i),
    .dc_latches_next_next_st_vaddy(dc_latches_next_next_st_vaddy_i),
    .dc_latches_next_st_laddy(dc_latches_next_st_laddy_i),
    .dc_latches_next_st_stack_access(dc_latches_next_st_stack_access_i),
    .dc_latches_next_NEIP(dc_latches_next_NEIP_i),
    .dc_latches_next_EIP(dc_latches_next_EIP_i),
    .dc_latches_next_EAX(dc_latches_next_EAX_i),
    .dc_latches_next_imm64(dc_latches_next_imm64_i),
    .dc_latches_next_sr_id(dc_latches_next_sr_id_i),
    .dc_latches_next_sr_data(dc_latches_next_sr_data_i),
    .dc_latches_next_dr_id(dc_latches_next_dr_id_i),
    .dc_latches_next_dr_data(dc_latches_next_dr_data_i),
    .outs_valid(outs_valid_i),
    .outs_stall(outs_stall_i),
    .outs_ecx_sb(outs_ecx_sb_i),
    .outs_ecx(outs_ecx_i),
    .outs_eax(outs_eax_i),
    .outs_set_ZF_sb(outs_set_ZF_sb_i),
    .outs_codeSeg_sb(outs_codeSeg_sb_i),
    .outs_codeSeg_data(outs_codeSeg_data_i),
    .outs_codeSeg_limit(outs_codeSeg_limit_i),
    .outs_dc_stage_latch_we(outs_dc_stage_latch_we_i),
    .outs_regFileValues_0(outs_regFileValues_0_i),    // CS
    .outs_regFileValues_1(outs_regFileValues_1_i),    // DS
    .outs_regFileValues_2(outs_regFileValues_2_i),    // SS
    .outs_regFileValues_3(outs_regFileValues_3_i),    // ES
    .outs_regFileValues_4(outs_regFileValues_4_i),    // FS
    .outs_regFileValues_5(outs_regFileValues_5_i),    // GS
    .outs_regFileValues_6(outs_regFileValues_6_i),    // EXPS
    .outs_regFileValues_7(outs_regFileValues_7_i),    // EAX
    .outs_regFileValues_8(outs_regFileValues_8_i),    // EBX
    .outs_regFileValues_9(outs_regFileValues_9_i),    // ECX
    .outs_regFileValues_10(outs_regFileValues_10_i),   // EDX
    .outs_regFileValues_11(outs_regFileValues_11_i),   // ESI
    .outs_regFileValues_12(outs_regFileValues_12_i),   // EDI
    .outs_regFileValues_13(outs_regFileValues_13_i),   // ESP
    .outs_regFileValues_14(outs_regFileValues_14_i),   // EBP
    .outs_regFileValues_15(outs_regFileValues_15_i),   // MM0
    .outs_regFileValues_16(outs_regFileValues_16_i),   // MM1
    .outs_regFileValues_17(outs_regFileValues_17_i),   // MM2
    .outs_regFileValues_18(outs_regFileValues_18_i),   // MM3
    .outs_regFileValues_19(outs_regFileValues_19_i),   // MM4
    .outs_regFileValues_20(outs_regFileValues_20_i),   // MM5
    .outs_regFileValues_21(outs_regFileValues_21_i),   // MM6
    .outs_regFileValues_22(outs_regFileValues_22_i),   // MM7
    .outs_regFileValues_23(outs_regFileValues_23_i),   // ETR
    .outs_regFileValues_24(outs_regFileValues_24_i),   // ERROR_REG
    .outs_regFileValues_25(outs_regFileValues_25_i)    // NO_REG
);

endmodule
