module tb_fanout;

 Fetch uut_fetch (
    .clk(clk_i),
    .rst(rst_i),
    .icache_info_hit(icache_info_hit_i),
    .icache_info_instruction_line(icache_info_instruction_line_i),
    .idm_info_idm_slots_0_valid(idm_info_idm_slots_0_valid_i),
    .idm_info_idm_slots_0_br_valid(idm_info_idm_slots_0_br_valid_i),
    .idm_info_idm_slots_0_br_eip(idm_info_idm_slots_0_br_eip_i),
    .idm_info_idm_slots_0_br_btb_target(idm_info_idm_slots_0_br_btb_target_i),
    .idm_info_idm_slots_0_br_xcl(idm_info_idm_slots_0_br_xcl_i),
    .idm_info_idm_slots_1_valid(idm_info_idm_slots_1_valid_i),
    .idm_info_idm_slots_1_br_valid(idm_info_idm_slots_1_br_valid_i),
    .idm_info_idm_slots_1_br_eip(idm_info_idm_slots_1_br_eip_i),
    .idm_info_idm_slots_1_br_btb_target(idm_info_idm_slots_1_br_btb_target_i),
    .idm_info_idm_slots_1_br_xcl(idm_info_idm_slots_1_br_xcl_i),
    .idm_info_idm_slots_2_valid(idm_info_idm_slots_2_valid_i),
    .idm_info_idm_slots_2_br_valid(idm_info_idm_slots_2_br_valid_i),
    .idm_info_idm_slots_2_br_eip(idm_info_idm_slots_2_br_eip_i),
    .idm_info_idm_slots_2_br_btb_target(idm_info_idm_slots_2_br_btb_target_i),
    .idm_info_idm_slots_2_br_xcl(idm_info_idm_slots_2_br_xcl_i),
    .idm_info_idm_slots_3_valid(idm_info_idm_slots_3_valid_i),
    .idm_info_idm_slots_3_br_valid(idm_info_idm_slots_3_br_valid_i),
    .idm_info_idm_slots_3_br_eip(idm_info_idm_slots_3_br_eip_i),
    .idm_info_idm_slots_3_br_btb_target(idm_info_idm_slots_3_br_btb_target_i),
    .idm_info_idm_slots_3_br_xcl(idm_info_idm_slots_3_br_xcl_i),
    .idm_info_valid_slots(idm_info_valid_slots_i),
    .decode_outs_invalid_instruction(decode_outs_invalid_instruction_i),
    .decode_outs_eip(decode_outs_eip_i),
    .decode_outs_decode_forward(decode_outs_decode_forward_i),
    .decode_outs_stall(decode_outs_stall_i),
    .rr_outs_valid(rr_outs_valid_i),
    .rr_outs_codeSeg_sb(rr_outs_codeSeg_sb_i),
    .rr_outs_codeSeg_data(rr_outs_codeSeg_data_i),
    .rr_outs_codeSeg_limit(rr_outs_codeSeg_limit_i),
    .dc_outs_valid(dc_outs_valid_i),
    .dc_outs_exp_present(dc_outs_exp_present_i),
    .dc_outs_exp_pf(dc_outs_exp_pf_i),
    .mem_outs_valid(mem_outs_valid_i),
    .exe_outs_valid(exe_outs_valid_i),
    // Fetch's exe_br_res_valid input was split per-consumer (BTB / Predictor /
    // Fetch top) at the EXE producer to break the 77-load fanout. The 3 valid
    // ports each carry the same logical value; drive them from the same _i wire.
    .exe_outs_br_res_valid_btb       (exe_outs_br_res_valid_i),
    .exe_outs_br_res_valid_pred      (exe_outs_br_res_valid_i),
    .exe_outs_br_res_valid_fetch     (exe_outs_br_res_valid_i),
    .exe_outs_br_res_flush(exe_outs_br_res_flush_i),
    .exe_outs_br_res_miss_prediction_pred(exe_outs_br_res_miss_prediction_i),
    .exe_outs_br_res_br_eip(exe_outs_br_res_br_eip_i),
    .exe_outs_br_res_neip(exe_outs_br_res_neip_i),
    .exe_outs_br_res_br_target(exe_outs_br_res_br_target_i),
    .exe_outs_br_res_taken(exe_outs_br_res_taken_i),
    .exe_outs_br_res_br_XCL(exe_outs_br_res_br_XCL_i),
    .exe_outs_br_res_clr_exp_mode(exe_outs_br_res_clr_exp_mode_i),
    .exe_outs_br_res_br_ucond(exe_outs_br_res_br_ucond_i),
    .wb_outs_valid(wb_outs_valid_i),
    .dma_int(dma_int_i),
    .outs_fetch_2_icache_icache_en(outs_fetch_2_icache_icache_en_i),
    .outs_fetch_2_icache_p_addr(outs_fetch_2_icache_p_addr_i),
    .outs_fetch_2_icache_v_addr_i(outs_fetch_2_icache_v_addr_i_i),
    .outs_fetch_2_icache_num_valid_IDM_slots(outs_fetch_2_icache_num_valid_IDM_slots_i),
    .outs_idm_reqs_req_0_ld_meta_data(outs_idm_reqs_req_0_ld_meta_data_i),
    .outs_idm_reqs_req_0_ld_data(outs_idm_reqs_req_0_ld_data_i),
    .outs_idm_reqs_req_0_valid(outs_idm_reqs_req_0_valid_i),
    .outs_idm_reqs_req_0_br_valid(outs_idm_reqs_req_0_br_valid_i),
    .outs_idm_reqs_req_0_br_eip(outs_idm_reqs_req_0_br_eip_i),
    .outs_idm_reqs_req_0_br_target(outs_idm_reqs_req_0_br_target_i),
    .outs_idm_reqs_req_0_br_xcl(outs_idm_reqs_req_0_br_xcl_i),
    .outs_idm_reqs_req_0_data(outs_idm_reqs_req_0_data_i),
    .outs_idm_reqs_req_2_ld_meta_data(outs_idm_reqs_req_2_ld_meta_data_i),
    .outs_idm_reqs_req_2_ld_data(outs_idm_reqs_req_2_ld_data_i),
    .outs_idm_reqs_req_2_valid(outs_idm_reqs_req_2_valid_i),
    .outs_idm_reqs_req_2_br_valid(outs_idm_reqs_req_2_br_valid_i),
    .outs_idm_reqs_req_2_br_eip(outs_idm_reqs_req_2_br_eip_i),
    .outs_idm_reqs_req_2_br_target(outs_idm_reqs_req_2_br_target_i),
    .outs_idm_reqs_req_2_br_xcl(outs_idm_reqs_req_2_br_xcl_i),
    .outs_idm_reqs_req_2_data(outs_idm_reqs_req_2_data_i),
    .outs_idm_reqs_req_3_ld_meta_data(outs_idm_reqs_req_3_ld_meta_data_i),
    .outs_idm_reqs_req_3_ld_data(outs_idm_reqs_req_3_ld_data_i),
    .outs_idm_reqs_req_3_valid(outs_idm_reqs_req_3_valid_i),
    .outs_idm_reqs_req_3_br_valid(outs_idm_reqs_req_3_br_valid_i),
    .outs_idm_reqs_req_3_br_eip(outs_idm_reqs_req_3_br_eip_i),
    .outs_idm_reqs_req_3_br_target(outs_idm_reqs_req_3_br_target_i),
    .outs_idm_reqs_req_3_br_xcl(outs_idm_reqs_req_3_br_xcl_i),
    .outs_idm_reqs_req_3_data(outs_idm_reqs_req_3_data_i),
    .outs_exp_pipe_clear(outs_exp_pipe_clear_i),
    .outs_exp_present(outs_exp_present_i),
    .outs_exp_pf(outs_exp_pf_i),
    .outs_exp_mode_jk(outs_exp_mode_jk_i),
    .outs_int_mode_jk()
);

endmodule
