// Auto-generated by csv_to_rom_verilog.py
// Module : control_store_genned
// Inputs : in_9_i, in_8_i, in_7_i, in_6_i, in_5_i, in_4_i, in_3_i, in_2_i, in_1_i, in_0_i
// Outputs: REP_o, MODRM_NEEDED_o, RM_IS_DR_o, REG_IS_DR_o, HARD_CODED_DR_o, HARD_CODED_DR_ID_4_o, HARD_CODED_DR_ID_3_o, HARD_CODED_DR_ID_2_o, HARD_CODED_DR_ID_1_o, HARD_CODED_DR_ID_0_o, HARD_CODED_SR_o, HARD_CODED_SR_ID_4_o, HARD_CODED_SR_ID_3_o, HARD_CODED_SR_ID_2_o, HARD_CODED_SR_ID_1_o, HARD_CODED_SR_ID_0_o, OP_IN_MODRM_o, DATA_SIZE_2_o, DATA_SIZE_1_o, DATA_SIZE_0_o, RR_OP_o, HARDCODED_DR_RD_o, HARDCODED_SR_RD_o, ST_SEL_o, DC_OP_o, MEM_OP_o, EXE_OP_o, alu_inputA_sel_4_o, alu_inputA_sel_3_o, alu_inputA_sel_2_o, alu_inputA_sel_1_o, alu_inputA_sel_0_o, alu_inputB_sel_4_o, alu_inputB_sel_3_o, alu_inputB_sel_2_o, alu_inputB_sel_1_o, alu_inputB_sel_0_o, branch_target_sel_4_o, branch_target_sel_3_o, branch_target_sel_2_o, branch_target_sel_1_o, branch_target_sel_0_o, OP_TYPE_4_o, OP_TYPE_3_o, OP_TYPE_2_o, OP_TYPE_1_o, OP_TYPE_0_o, br_uncond_o, relative_branch_o, special_dr_o, is_far_o, second_flag_needed_o, WB_OP_o
// ROMs   : 32 instance(s) per bank  x  1 bank(s)
//          ROM addr width = 5 bit(s),  select width = 5 bit(s)
`timescale 1ns/1ps

module control_store_genned (
    input  wire in_9_i,
    input  wire in_8_i,
    input  wire in_7_i,
    input  wire in_6_i,
    input  wire in_5_i,
    input  wire in_4_i,
    input  wire in_3_i,
    input  wire in_2_i,
    input  wire in_1_i,
    input  wire in_0_i,
    output wire REP_o,
    output wire MODRM_NEEDED_o,
    output wire RM_IS_DR_o,
    output wire REG_IS_DR_o,
    output wire HARD_CODED_DR_o,
    output wire HARD_CODED_DR_ID_4_o,
    output wire HARD_CODED_DR_ID_3_o,
    output wire HARD_CODED_DR_ID_2_o,
    output wire HARD_CODED_DR_ID_1_o,
    output wire HARD_CODED_DR_ID_0_o,
    output wire HARD_CODED_SR_o,
    output wire HARD_CODED_SR_ID_4_o,
    output wire HARD_CODED_SR_ID_3_o,
    output wire HARD_CODED_SR_ID_2_o,
    output wire HARD_CODED_SR_ID_1_o,
    output wire HARD_CODED_SR_ID_0_o,
    output wire OP_IN_MODRM_o,
    output wire DATA_SIZE_2_o,
    output wire DATA_SIZE_1_o,
    output wire DATA_SIZE_0_o,
    output wire RR_OP_o,
    output wire HARDCODED_DR_RD_o,
    output wire HARDCODED_SR_RD_o,
    output wire ST_SEL_o,
    output wire DC_OP_o,
    output wire MEM_OP_o,
    output wire EXE_OP_o,
    output wire alu_inputA_sel_4_o,
    output wire alu_inputA_sel_3_o,
    output wire alu_inputA_sel_2_o,
    output wire alu_inputA_sel_1_o,
    output wire alu_inputA_sel_0_o,
    output wire alu_inputB_sel_4_o,
    output wire alu_inputB_sel_3_o,
    output wire alu_inputB_sel_2_o,
    output wire alu_inputB_sel_1_o,
    output wire alu_inputB_sel_0_o,
    output wire branch_target_sel_4_o,
    output wire branch_target_sel_3_o,
    output wire branch_target_sel_2_o,
    output wire branch_target_sel_1_o,
    output wire branch_target_sel_0_o,
    output wire OP_TYPE_4_o,
    output wire OP_TYPE_3_o,
    output wire OP_TYPE_2_o,
    output wire OP_TYPE_1_o,
    output wire OP_TYPE_0_o,
    output wire br_uncond_o,
    output wire relative_branch_o,
    output wire special_dr_o,
    output wire is_far_o,
    output wire second_flag_needed_o,
    output wire WB_OP_o
);

    // Address = lower 5 input bit(s)
    wire [4:0] addr = { in_4_i, in_3_i, in_2_i, in_1_i, in_0_i };
    // Select  = upper 5 input bit(s) → chooses which ROM drives the bus
    wire [4:0] sel = { in_9_i, in_8_i, in_7_i, in_6_i, in_5_i };

    // Bank 0: dout_bus_0 carries output bits [52:0]
    wire [63:0] dout_bus_0;

    assign REP_o = dout_bus_0[0];
    assign MODRM_NEEDED_o = dout_bus_0[1];
    assign RM_IS_DR_o = dout_bus_0[2];
    assign REG_IS_DR_o = dout_bus_0[3];
    assign HARD_CODED_DR_o = dout_bus_0[4];
    assign HARD_CODED_DR_ID_4_o = dout_bus_0[5];
    assign HARD_CODED_DR_ID_3_o = dout_bus_0[6];
    assign HARD_CODED_DR_ID_2_o = dout_bus_0[7];
    assign HARD_CODED_DR_ID_1_o = dout_bus_0[8];
    assign HARD_CODED_DR_ID_0_o = dout_bus_0[9];
    assign HARD_CODED_SR_o = dout_bus_0[10];
    assign HARD_CODED_SR_ID_4_o = dout_bus_0[11];
    assign HARD_CODED_SR_ID_3_o = dout_bus_0[12];
    assign HARD_CODED_SR_ID_2_o = dout_bus_0[13];
    assign HARD_CODED_SR_ID_1_o = dout_bus_0[14];
    assign HARD_CODED_SR_ID_0_o = dout_bus_0[15];
    assign OP_IN_MODRM_o = dout_bus_0[16];
    assign DATA_SIZE_2_o = dout_bus_0[17];
    assign DATA_SIZE_1_o = dout_bus_0[18];
    assign DATA_SIZE_0_o = dout_bus_0[19];
    assign RR_OP_o = dout_bus_0[20];
    assign HARDCODED_DR_RD_o = dout_bus_0[21];
    assign HARDCODED_SR_RD_o = dout_bus_0[22];
    assign ST_SEL_o = dout_bus_0[23];
    assign DC_OP_o = dout_bus_0[24];
    assign MEM_OP_o = dout_bus_0[25];
    assign EXE_OP_o = dout_bus_0[26];
    assign alu_inputA_sel_4_o = dout_bus_0[27];
    assign alu_inputA_sel_3_o = dout_bus_0[28];
    assign alu_inputA_sel_2_o = dout_bus_0[29];
    assign alu_inputA_sel_1_o = dout_bus_0[30];
    assign alu_inputA_sel_0_o = dout_bus_0[31];
    assign alu_inputB_sel_4_o = dout_bus_0[32];
    assign alu_inputB_sel_3_o = dout_bus_0[33];
    assign alu_inputB_sel_2_o = dout_bus_0[34];
    assign alu_inputB_sel_1_o = dout_bus_0[35];
    assign alu_inputB_sel_0_o = dout_bus_0[36];
    assign branch_target_sel_4_o = dout_bus_0[37];
    assign branch_target_sel_3_o = dout_bus_0[38];
    assign branch_target_sel_2_o = dout_bus_0[39];
    assign branch_target_sel_1_o = dout_bus_0[40];
    assign branch_target_sel_0_o = dout_bus_0[41];
    assign OP_TYPE_4_o = dout_bus_0[42];
    assign OP_TYPE_3_o = dout_bus_0[43];
    assign OP_TYPE_2_o = dout_bus_0[44];
    assign OP_TYPE_1_o = dout_bus_0[45];
    assign OP_TYPE_0_o = dout_bus_0[46];
    assign br_uncond_o = dout_bus_0[47];
    assign relative_branch_o = dout_bus_0[48];
    assign special_dr_o = dout_bus_0[49];
    assign is_far_o = dout_bus_0[50];
    assign second_flag_needed_o = dout_bus_0[51];
    assign WB_OP_o = dout_bus_0[52];

    // ────────────────────────────────────────────────────────────
    // Bank 0
    // ────────────────────────────────────────────────────────────

    // Bank 0, ROM 00  (sel == 5'b00000)
    wire oe_b0_00 = (sel == 5'd0);
    rom64b32w$ u_rom_b0_00 (
        .A    (addr),
        .OE   (oe_b0_00),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_00.mem[ 0] = 64'h0010401047101866;
        u_rom_b0_00.mem[ 1] = 64'h0010401047101866;
        u_rom_b0_00.mem[ 2] = 64'h0010401047101866;
        u_rom_b0_00.mem[ 3] = 64'h0010401047101866;
        u_rom_b0_00.mem[ 4] = 64'h001040104710186A;
        u_rom_b0_00.mem[ 5] = 64'h001040104710186A;
        u_rom_b0_00.mem[ 6] = 64'h001040104710186A;
        u_rom_b0_00.mem[ 7] = 64'h001040104710186A;
        u_rom_b0_00.mem[ 8] = 64'h0010400247301990;
        u_rom_b0_00.mem[ 9] = 64'h0010400247301990;
        u_rom_b0_00.mem[10] = 64'h0010400247301990;
        u_rom_b0_00.mem[11] = 64'h0010400247301990;
        u_rom_b0_00.mem[12] = 64'h00000C1044001B10;
        u_rom_b0_00.mem[13] = 64'h00000C1044001B10;
        u_rom_b0_00.mem[14] = 64'h00007410C4001B10;
        u_rom_b0_00.mem[15] = 64'h00007410C4001B10;
        u_rom_b0_00.mem[16] = 64'h0000000000000000;
        u_rom_b0_00.mem[17] = 64'h0000000000000000;
        u_rom_b0_00.mem[18] = 64'h0000000000000000;
        u_rom_b0_00.mem[19] = 64'h0000000000000000;
        u_rom_b0_00.mem[20] = 64'h0000000000000000;
        u_rom_b0_00.mem[21] = 64'h0000000000000000;
        u_rom_b0_00.mem[22] = 64'h0000000000000000;
        u_rom_b0_00.mem[23] = 64'h0000000000000000;
        u_rom_b0_00.mem[24] = 64'h0000000000000000;
        u_rom_b0_00.mem[25] = 64'h0000000000000000;
        u_rom_b0_00.mem[26] = 64'h0000000000000000;
        u_rom_b0_00.mem[27] = 64'h0000000000000000;
        u_rom_b0_00.mem[28] = 64'h0000000000000000;
        u_rom_b0_00.mem[29] = 64'h0000000000000000;
        u_rom_b0_00.mem[30] = 64'h0000000000000000;
        u_rom_b0_00.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 01  (sel == 5'b00001)
    wire oe_b0_01 = (sel == 5'd1);
    rom64b32w$ u_rom_b0_01 (
        .A    (addr),
        .OE   (oe_b0_01),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_01.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_01.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_01.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_01.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_01.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_01.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_01.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_01.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_01.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_01.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_01.mem[10] = 64'h0000000000000000;
        u_rom_b0_01.mem[11] = 64'h0000000000000000;
        u_rom_b0_01.mem[12] = 64'h0000000000000000;
        u_rom_b0_01.mem[13] = 64'h0000000000000000;
        u_rom_b0_01.mem[14] = 64'h0000000000000000;
        u_rom_b0_01.mem[15] = 64'h0000000000000000;
        u_rom_b0_01.mem[16] = 64'h0000000000000000;
        u_rom_b0_01.mem[17] = 64'h0000000000000000;
        u_rom_b0_01.mem[18] = 64'h0000000000000000;
        u_rom_b0_01.mem[19] = 64'h0000000000000000;
        u_rom_b0_01.mem[20] = 64'h0000000000000000;
        u_rom_b0_01.mem[21] = 64'h0000000000000000;
        u_rom_b0_01.mem[22] = 64'h0000000000000000;
        u_rom_b0_01.mem[23] = 64'h0000000000000000;
        u_rom_b0_01.mem[24] = 64'h0000000000000000;
        u_rom_b0_01.mem[25] = 64'h0000000000000000;
        u_rom_b0_01.mem[26] = 64'h0000000000000000;
        u_rom_b0_01.mem[27] = 64'h0000000000000000;
        u_rom_b0_01.mem[28] = 64'h0000000000000000;
        u_rom_b0_01.mem[29] = 64'h0000000000000000;
        u_rom_b0_01.mem[30] = 64'h0000000000000000;
        u_rom_b0_01.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 02  (sel == 5'b00010)
    wire oe_b0_02 = (sel == 5'd2);
    rom64b32w$ u_rom_b0_02 (
        .A    (addr),
        .OE   (oe_b0_02),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_02.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_02.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_02.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_02.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_02.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_02.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_02.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_02.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_02.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_02.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_02.mem[10] = 64'h0000000000000000;
        u_rom_b0_02.mem[11] = 64'h0000000000000000;
        u_rom_b0_02.mem[12] = 64'h0000000000000000;
        u_rom_b0_02.mem[13] = 64'h0000000000000000;
        u_rom_b0_02.mem[14] = 64'h0000000000000000;
        u_rom_b0_02.mem[15] = 64'h0000000000000000;
        u_rom_b0_02.mem[16] = 64'h0000000000000000;
        u_rom_b0_02.mem[17] = 64'h0000000000000000;
        u_rom_b0_02.mem[18] = 64'h0000000000000000;
        u_rom_b0_02.mem[19] = 64'h0000000000000000;
        u_rom_b0_02.mem[20] = 64'h0000000000000000;
        u_rom_b0_02.mem[21] = 64'h0000000000000000;
        u_rom_b0_02.mem[22] = 64'h0000000000000000;
        u_rom_b0_02.mem[23] = 64'h0000000000000000;
        u_rom_b0_02.mem[24] = 64'h0000000000000000;
        u_rom_b0_02.mem[25] = 64'h0000000000000000;
        u_rom_b0_02.mem[26] = 64'h0000000000000000;
        u_rom_b0_02.mem[27] = 64'h0000000000000000;
        u_rom_b0_02.mem[28] = 64'h0000000000000000;
        u_rom_b0_02.mem[29] = 64'h0000000000000000;
        u_rom_b0_02.mem[30] = 64'h0000000000000000;
        u_rom_b0_02.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 03  (sel == 5'b00011)
    wire oe_b0_03 = (sel == 5'd3);
    rom64b32w$ u_rom_b0_03 (
        .A    (addr),
        .OE   (oe_b0_03),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_03.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_03.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_03.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_03.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_03.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_03.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_03.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_03.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_03.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_03.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_03.mem[10] = 64'h0000000000000000;
        u_rom_b0_03.mem[11] = 64'h0000000000000000;
        u_rom_b0_03.mem[12] = 64'h0000000000000000;
        u_rom_b0_03.mem[13] = 64'h0000000000000000;
        u_rom_b0_03.mem[14] = 64'h0000000000000000;
        u_rom_b0_03.mem[15] = 64'h0000000000000000;
        u_rom_b0_03.mem[16] = 64'h0000000000000000;
        u_rom_b0_03.mem[17] = 64'h0000000000000000;
        u_rom_b0_03.mem[18] = 64'h0000000000000000;
        u_rom_b0_03.mem[19] = 64'h0000000000000000;
        u_rom_b0_03.mem[20] = 64'h0000000000000000;
        u_rom_b0_03.mem[21] = 64'h0000000000000000;
        u_rom_b0_03.mem[22] = 64'h0000000000000000;
        u_rom_b0_03.mem[23] = 64'h0000000000000000;
        u_rom_b0_03.mem[24] = 64'h0000000000000000;
        u_rom_b0_03.mem[25] = 64'h0000000000000000;
        u_rom_b0_03.mem[26] = 64'h0000000000000000;
        u_rom_b0_03.mem[27] = 64'h0000000000000000;
        u_rom_b0_03.mem[28] = 64'h0000000000000000;
        u_rom_b0_03.mem[29] = 64'h0000000000000000;
        u_rom_b0_03.mem[30] = 64'h0000000000000000;
        u_rom_b0_03.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 04  (sel == 5'b00100)
    wire oe_b0_04 = (sel == 5'd4);
    rom64b32w$ u_rom_b0_04 (
        .A    (addr),
        .OE   (oe_b0_04),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_04.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_04.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_04.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_04.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_04.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_04.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_04.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_04.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_04.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_04.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_04.mem[10] = 64'h0000000000000000;
        u_rom_b0_04.mem[11] = 64'h0000000000000000;
        u_rom_b0_04.mem[12] = 64'h0000000000000000;
        u_rom_b0_04.mem[13] = 64'h0000000000000000;
        u_rom_b0_04.mem[14] = 64'h0000000000000000;
        u_rom_b0_04.mem[15] = 64'h0000000000000000;
        u_rom_b0_04.mem[16] = 64'h0000000000000000;
        u_rom_b0_04.mem[17] = 64'h0000000000000000;
        u_rom_b0_04.mem[18] = 64'h0000000000000000;
        u_rom_b0_04.mem[19] = 64'h0000000000000000;
        u_rom_b0_04.mem[20] = 64'h0000000000000000;
        u_rom_b0_04.mem[21] = 64'h0000000000000000;
        u_rom_b0_04.mem[22] = 64'h0000000000000000;
        u_rom_b0_04.mem[23] = 64'h0000000000000000;
        u_rom_b0_04.mem[24] = 64'h0000000000000000;
        u_rom_b0_04.mem[25] = 64'h0000000000000000;
        u_rom_b0_04.mem[26] = 64'h0000000000000000;
        u_rom_b0_04.mem[27] = 64'h0000000000000000;
        u_rom_b0_04.mem[28] = 64'h0000000000000000;
        u_rom_b0_04.mem[29] = 64'h0000000000000000;
        u_rom_b0_04.mem[30] = 64'h0000000000000000;
        u_rom_b0_04.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 05  (sel == 5'b00101)
    wire oe_b0_05 = (sel == 5'd5);
    rom64b32w$ u_rom_b0_05 (
        .A    (addr),
        .OE   (oe_b0_05),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_05.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_05.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_05.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_05.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_05.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_05.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_05.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_05.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_05.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_05.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_05.mem[10] = 64'h0000000000000000;
        u_rom_b0_05.mem[11] = 64'h0000000000000000;
        u_rom_b0_05.mem[12] = 64'h0000000000000000;
        u_rom_b0_05.mem[13] = 64'h0000000000000000;
        u_rom_b0_05.mem[14] = 64'h0000000000000000;
        u_rom_b0_05.mem[15] = 64'h0000000000000000;
        u_rom_b0_05.mem[16] = 64'h0000000000000000;
        u_rom_b0_05.mem[17] = 64'h0000000000000000;
        u_rom_b0_05.mem[18] = 64'h0000000000000000;
        u_rom_b0_05.mem[19] = 64'h0000000000000000;
        u_rom_b0_05.mem[20] = 64'h0000000000000000;
        u_rom_b0_05.mem[21] = 64'h0000000000000000;
        u_rom_b0_05.mem[22] = 64'h0000000000000000;
        u_rom_b0_05.mem[23] = 64'h0000000000000000;
        u_rom_b0_05.mem[24] = 64'h0000000000000000;
        u_rom_b0_05.mem[25] = 64'h0000000000000000;
        u_rom_b0_05.mem[26] = 64'h0000000000000000;
        u_rom_b0_05.mem[27] = 64'h0000000000000000;
        u_rom_b0_05.mem[28] = 64'h0000000000000000;
        u_rom_b0_05.mem[29] = 64'h0000000000000000;
        u_rom_b0_05.mem[30] = 64'h0000000000000000;
        u_rom_b0_05.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 06  (sel == 5'b00110)
    wire oe_b0_06 = (sel == 5'd6);
    rom64b32w$ u_rom_b0_06 (
        .A    (addr),
        .OE   (oe_b0_06),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_06.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_06.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_06.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_06.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_06.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_06.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_06.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_06.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_06.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_06.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_06.mem[10] = 64'h0000000000000000;
        u_rom_b0_06.mem[11] = 64'h0000000000000000;
        u_rom_b0_06.mem[12] = 64'h0000000000000000;
        u_rom_b0_06.mem[13] = 64'h0000000000000000;
        u_rom_b0_06.mem[14] = 64'h0000000000000000;
        u_rom_b0_06.mem[15] = 64'h0000000000000000;
        u_rom_b0_06.mem[16] = 64'h0000000000000000;
        u_rom_b0_06.mem[17] = 64'h0000000000000000;
        u_rom_b0_06.mem[18] = 64'h0000000000000000;
        u_rom_b0_06.mem[19] = 64'h0000000000000000;
        u_rom_b0_06.mem[20] = 64'h0000000000000000;
        u_rom_b0_06.mem[21] = 64'h0000000000000000;
        u_rom_b0_06.mem[22] = 64'h0000000000000000;
        u_rom_b0_06.mem[23] = 64'h0000000000000000;
        u_rom_b0_06.mem[24] = 64'h0000000000000000;
        u_rom_b0_06.mem[25] = 64'h0000000000000000;
        u_rom_b0_06.mem[26] = 64'h0000000000000000;
        u_rom_b0_06.mem[27] = 64'h0000000000000000;
        u_rom_b0_06.mem[28] = 64'h0000000000000000;
        u_rom_b0_06.mem[29] = 64'h0000000000000000;
        u_rom_b0_06.mem[30] = 64'h0000000000000000;
        u_rom_b0_06.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 07  (sel == 5'b00111)
    wire oe_b0_07 = (sel == 5'd7);
    rom64b32w$ u_rom_b0_07 (
        .A    (addr),
        .OE   (oe_b0_07),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_07.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_07.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_07.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_07.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_07.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_07.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_07.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_07.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_07.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_07.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_07.mem[10] = 64'h0000000000000000;
        u_rom_b0_07.mem[11] = 64'h0000000000000000;
        u_rom_b0_07.mem[12] = 64'h0000000000000000;
        u_rom_b0_07.mem[13] = 64'h0000000000000000;
        u_rom_b0_07.mem[14] = 64'h0000000000000000;
        u_rom_b0_07.mem[15] = 64'h0000000000000000;
        u_rom_b0_07.mem[16] = 64'h0000000000000000;
        u_rom_b0_07.mem[17] = 64'h0000000000000000;
        u_rom_b0_07.mem[18] = 64'h0000000000000000;
        u_rom_b0_07.mem[19] = 64'h0000000000000000;
        u_rom_b0_07.mem[20] = 64'h0000000000000000;
        u_rom_b0_07.mem[21] = 64'h0000000000000000;
        u_rom_b0_07.mem[22] = 64'h0000000000000000;
        u_rom_b0_07.mem[23] = 64'h0000000000000000;
        u_rom_b0_07.mem[24] = 64'h0000000000000000;
        u_rom_b0_07.mem[25] = 64'h0000000000000000;
        u_rom_b0_07.mem[26] = 64'h0000000000000000;
        u_rom_b0_07.mem[27] = 64'h0000000000000000;
        u_rom_b0_07.mem[28] = 64'h0000000000000000;
        u_rom_b0_07.mem[29] = 64'h0000000000000000;
        u_rom_b0_07.mem[30] = 64'h0000000000000000;
        u_rom_b0_07.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 08  (sel == 5'b01000)
    wire oe_b0_08 = (sel == 5'd8);
    rom64b32w$ u_rom_b0_08 (
        .A    (addr),
        .OE   (oe_b0_08),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_08.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_08.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_08.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_08.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_08.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_08.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_08.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_08.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_08.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_08.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_08.mem[10] = 64'h0000000000000000;
        u_rom_b0_08.mem[11] = 64'h0000000000000000;
        u_rom_b0_08.mem[12] = 64'h0000000000000000;
        u_rom_b0_08.mem[13] = 64'h0000000000000000;
        u_rom_b0_08.mem[14] = 64'h0000000000000000;
        u_rom_b0_08.mem[15] = 64'h0000000000000000;
        u_rom_b0_08.mem[16] = 64'h0000000000000000;
        u_rom_b0_08.mem[17] = 64'h0000000000000000;
        u_rom_b0_08.mem[18] = 64'h0000000000000000;
        u_rom_b0_08.mem[19] = 64'h0000000000000000;
        u_rom_b0_08.mem[20] = 64'h0000000000000000;
        u_rom_b0_08.mem[21] = 64'h0000000000000000;
        u_rom_b0_08.mem[22] = 64'h0000000000000000;
        u_rom_b0_08.mem[23] = 64'h0000000000000000;
        u_rom_b0_08.mem[24] = 64'h0000000000000000;
        u_rom_b0_08.mem[25] = 64'h0000000000000000;
        u_rom_b0_08.mem[26] = 64'h0000000000000000;
        u_rom_b0_08.mem[27] = 64'h0000000000000000;
        u_rom_b0_08.mem[28] = 64'h0000000000000000;
        u_rom_b0_08.mem[29] = 64'h0000000000000000;
        u_rom_b0_08.mem[30] = 64'h0000000000000000;
        u_rom_b0_08.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 09  (sel == 5'b01001)
    wire oe_b0_09 = (sel == 5'd9);
    rom64b32w$ u_rom_b0_09 (
        .A    (addr),
        .OE   (oe_b0_09),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_09.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_09.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_09.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_09.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_09.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_09.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_09.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_09.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_09.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_09.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_09.mem[10] = 64'h0000000000000000;
        u_rom_b0_09.mem[11] = 64'h0000000000000000;
        u_rom_b0_09.mem[12] = 64'h0000000000000000;
        u_rom_b0_09.mem[13] = 64'h0000000000000000;
        u_rom_b0_09.mem[14] = 64'h0000000000000000;
        u_rom_b0_09.mem[15] = 64'h0000000000000000;
        u_rom_b0_09.mem[16] = 64'h0000000000000000;
        u_rom_b0_09.mem[17] = 64'h0000000000000000;
        u_rom_b0_09.mem[18] = 64'h0000000000000000;
        u_rom_b0_09.mem[19] = 64'h0000000000000000;
        u_rom_b0_09.mem[20] = 64'h0000000000000000;
        u_rom_b0_09.mem[21] = 64'h0000000000000000;
        u_rom_b0_09.mem[22] = 64'h0000000000000000;
        u_rom_b0_09.mem[23] = 64'h0000000000000000;
        u_rom_b0_09.mem[24] = 64'h0000000000000000;
        u_rom_b0_09.mem[25] = 64'h0000000000000000;
        u_rom_b0_09.mem[26] = 64'h0000000000000000;
        u_rom_b0_09.mem[27] = 64'h0000000000000000;
        u_rom_b0_09.mem[28] = 64'h0000000000000000;
        u_rom_b0_09.mem[29] = 64'h0000000000000000;
        u_rom_b0_09.mem[30] = 64'h0000000000000000;
        u_rom_b0_09.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 10  (sel == 5'b01010)
    wire oe_b0_10 = (sel == 5'd10);
    rom64b32w$ u_rom_b0_10 (
        .A    (addr),
        .OE   (oe_b0_10),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_10.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_10.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_10.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_10.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_10.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_10.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_10.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_10.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_10.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_10.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_10.mem[10] = 64'h0000000000000000;
        u_rom_b0_10.mem[11] = 64'h0000000000000000;
        u_rom_b0_10.mem[12] = 64'h0000000000000000;
        u_rom_b0_10.mem[13] = 64'h0000000000000000;
        u_rom_b0_10.mem[14] = 64'h0000000000000000;
        u_rom_b0_10.mem[15] = 64'h0000000000000000;
        u_rom_b0_10.mem[16] = 64'h0000000000000000;
        u_rom_b0_10.mem[17] = 64'h0000000000000000;
        u_rom_b0_10.mem[18] = 64'h0000000000000000;
        u_rom_b0_10.mem[19] = 64'h0000000000000000;
        u_rom_b0_10.mem[20] = 64'h0000000000000000;
        u_rom_b0_10.mem[21] = 64'h0000000000000000;
        u_rom_b0_10.mem[22] = 64'h0000000000000000;
        u_rom_b0_10.mem[23] = 64'h0000000000000000;
        u_rom_b0_10.mem[24] = 64'h0000000000000000;
        u_rom_b0_10.mem[25] = 64'h0000000000000000;
        u_rom_b0_10.mem[26] = 64'h0000000000000000;
        u_rom_b0_10.mem[27] = 64'h0000000000000000;
        u_rom_b0_10.mem[28] = 64'h0000000000000000;
        u_rom_b0_10.mem[29] = 64'h0000000000000000;
        u_rom_b0_10.mem[30] = 64'h0000000000000000;
        u_rom_b0_10.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 11  (sel == 5'b01011)
    wire oe_b0_11 = (sel == 5'd11);
    rom64b32w$ u_rom_b0_11 (
        .A    (addr),
        .OE   (oe_b0_11),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_11.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_11.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_11.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_11.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_11.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_11.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_11.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_11.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_11.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_11.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_11.mem[10] = 64'h0000000000000000;
        u_rom_b0_11.mem[11] = 64'h0000000000000000;
        u_rom_b0_11.mem[12] = 64'h0000000000000000;
        u_rom_b0_11.mem[13] = 64'h0000000000000000;
        u_rom_b0_11.mem[14] = 64'h0000000000000000;
        u_rom_b0_11.mem[15] = 64'h0000000000000000;
        u_rom_b0_11.mem[16] = 64'h0000000000000000;
        u_rom_b0_11.mem[17] = 64'h0000000000000000;
        u_rom_b0_11.mem[18] = 64'h0000000000000000;
        u_rom_b0_11.mem[19] = 64'h0000000000000000;
        u_rom_b0_11.mem[20] = 64'h0000000000000000;
        u_rom_b0_11.mem[21] = 64'h0000000000000000;
        u_rom_b0_11.mem[22] = 64'h0000000000000000;
        u_rom_b0_11.mem[23] = 64'h0000000000000000;
        u_rom_b0_11.mem[24] = 64'h0000000000000000;
        u_rom_b0_11.mem[25] = 64'h0000000000000000;
        u_rom_b0_11.mem[26] = 64'h0000000000000000;
        u_rom_b0_11.mem[27] = 64'h0000000000000000;
        u_rom_b0_11.mem[28] = 64'h0000000000000000;
        u_rom_b0_11.mem[29] = 64'h0000000000000000;
        u_rom_b0_11.mem[30] = 64'h0000000000000000;
        u_rom_b0_11.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 12  (sel == 5'b01100)
    wire oe_b0_12 = (sel == 5'd12);
    rom64b32w$ u_rom_b0_12 (
        .A    (addr),
        .OE   (oe_b0_12),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_12.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_12.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_12.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_12.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_12.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_12.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_12.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_12.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_12.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_12.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_12.mem[10] = 64'h0000000000000000;
        u_rom_b0_12.mem[11] = 64'h0000000000000000;
        u_rom_b0_12.mem[12] = 64'h0000000000000000;
        u_rom_b0_12.mem[13] = 64'h0000000000000000;
        u_rom_b0_12.mem[14] = 64'h0000000000000000;
        u_rom_b0_12.mem[15] = 64'h0000000000000000;
        u_rom_b0_12.mem[16] = 64'h0000000000000000;
        u_rom_b0_12.mem[17] = 64'h0000000000000000;
        u_rom_b0_12.mem[18] = 64'h0000000000000000;
        u_rom_b0_12.mem[19] = 64'h0000000000000000;
        u_rom_b0_12.mem[20] = 64'h0000000000000000;
        u_rom_b0_12.mem[21] = 64'h0000000000000000;
        u_rom_b0_12.mem[22] = 64'h0000000000000000;
        u_rom_b0_12.mem[23] = 64'h0000000000000000;
        u_rom_b0_12.mem[24] = 64'h0000000000000000;
        u_rom_b0_12.mem[25] = 64'h0000000000000000;
        u_rom_b0_12.mem[26] = 64'h0000000000000000;
        u_rom_b0_12.mem[27] = 64'h0000000000000000;
        u_rom_b0_12.mem[28] = 64'h0000000000000000;
        u_rom_b0_12.mem[29] = 64'h0000000000000000;
        u_rom_b0_12.mem[30] = 64'h0000000000000000;
        u_rom_b0_12.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 13  (sel == 5'b01101)
    wire oe_b0_13 = (sel == 5'd13);
    rom64b32w$ u_rom_b0_13 (
        .A    (addr),
        .OE   (oe_b0_13),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_13.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_13.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_13.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_13.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_13.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_13.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_13.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_13.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_13.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_13.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_13.mem[10] = 64'h0000000000000000;
        u_rom_b0_13.mem[11] = 64'h0000000000000000;
        u_rom_b0_13.mem[12] = 64'h0000000000000000;
        u_rom_b0_13.mem[13] = 64'h0000000000000000;
        u_rom_b0_13.mem[14] = 64'h0000000000000000;
        u_rom_b0_13.mem[15] = 64'h0000000000000000;
        u_rom_b0_13.mem[16] = 64'h0000000000000000;
        u_rom_b0_13.mem[17] = 64'h0000000000000000;
        u_rom_b0_13.mem[18] = 64'h0000000000000000;
        u_rom_b0_13.mem[19] = 64'h0000000000000000;
        u_rom_b0_13.mem[20] = 64'h0000000000000000;
        u_rom_b0_13.mem[21] = 64'h0000000000000000;
        u_rom_b0_13.mem[22] = 64'h0000000000000000;
        u_rom_b0_13.mem[23] = 64'h0000000000000000;
        u_rom_b0_13.mem[24] = 64'h0000000000000000;
        u_rom_b0_13.mem[25] = 64'h0000000000000000;
        u_rom_b0_13.mem[26] = 64'h0000000000000000;
        u_rom_b0_13.mem[27] = 64'h0000000000000000;
        u_rom_b0_13.mem[28] = 64'h0000000000000000;
        u_rom_b0_13.mem[29] = 64'h0000000000000000;
        u_rom_b0_13.mem[30] = 64'h0000000000000000;
        u_rom_b0_13.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 14  (sel == 5'b01110)
    wire oe_b0_14 = (sel == 5'd14);
    rom64b32w$ u_rom_b0_14 (
        .A    (addr),
        .OE   (oe_b0_14),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_14.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_14.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_14.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_14.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_14.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_14.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_14.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_14.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_14.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_14.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_14.mem[10] = 64'h0000000000000000;
        u_rom_b0_14.mem[11] = 64'h0000000000000000;
        u_rom_b0_14.mem[12] = 64'h0000000000000000;
        u_rom_b0_14.mem[13] = 64'h0000000000000000;
        u_rom_b0_14.mem[14] = 64'h0000000000000000;
        u_rom_b0_14.mem[15] = 64'h0000000000000000;
        u_rom_b0_14.mem[16] = 64'h0000000000000000;
        u_rom_b0_14.mem[17] = 64'h0000000000000000;
        u_rom_b0_14.mem[18] = 64'h0000000000000000;
        u_rom_b0_14.mem[19] = 64'h0000000000000000;
        u_rom_b0_14.mem[20] = 64'h0000000000000000;
        u_rom_b0_14.mem[21] = 64'h0000000000000000;
        u_rom_b0_14.mem[22] = 64'h0000000000000000;
        u_rom_b0_14.mem[23] = 64'h0000000000000000;
        u_rom_b0_14.mem[24] = 64'h0000000000000000;
        u_rom_b0_14.mem[25] = 64'h0000000000000000;
        u_rom_b0_14.mem[26] = 64'h0000000000000000;
        u_rom_b0_14.mem[27] = 64'h0000000000000000;
        u_rom_b0_14.mem[28] = 64'h0000000000000000;
        u_rom_b0_14.mem[29] = 64'h0000000000000000;
        u_rom_b0_14.mem[30] = 64'h0000000000000000;
        u_rom_b0_14.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 15  (sel == 5'b01111)
    wire oe_b0_15 = (sel == 5'd15);
    rom64b32w$ u_rom_b0_15 (
        .A    (addr),
        .OE   (oe_b0_15),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_15.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_15.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_15.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_15.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_15.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_15.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_15.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_15.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_15.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_15.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_15.mem[10] = 64'h0000000000000000;
        u_rom_b0_15.mem[11] = 64'h0000000000000000;
        u_rom_b0_15.mem[12] = 64'h0000000000000000;
        u_rom_b0_15.mem[13] = 64'h0000000000000000;
        u_rom_b0_15.mem[14] = 64'h0000000000000000;
        u_rom_b0_15.mem[15] = 64'h0000000000000000;
        u_rom_b0_15.mem[16] = 64'h0000000000000000;
        u_rom_b0_15.mem[17] = 64'h0000000000000000;
        u_rom_b0_15.mem[18] = 64'h0000000000000000;
        u_rom_b0_15.mem[19] = 64'h0000000000000000;
        u_rom_b0_15.mem[20] = 64'h0000000000000000;
        u_rom_b0_15.mem[21] = 64'h0000000000000000;
        u_rom_b0_15.mem[22] = 64'h0000000000000000;
        u_rom_b0_15.mem[23] = 64'h0000000000000000;
        u_rom_b0_15.mem[24] = 64'h0000000000000000;
        u_rom_b0_15.mem[25] = 64'h0000000000000000;
        u_rom_b0_15.mem[26] = 64'h0000000000000000;
        u_rom_b0_15.mem[27] = 64'h0000000000000000;
        u_rom_b0_15.mem[28] = 64'h0000000000000000;
        u_rom_b0_15.mem[29] = 64'h0000000000000000;
        u_rom_b0_15.mem[30] = 64'h0000000000000000;
        u_rom_b0_15.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 16  (sel == 5'b10000)
    wire oe_b0_16 = (sel == 5'd16);
    rom64b32w$ u_rom_b0_16 (
        .A    (addr),
        .OE   (oe_b0_16),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_16.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_16.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_16.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_16.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_16.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_16.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_16.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_16.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_16.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_16.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_16.mem[10] = 64'h0000000000000000;
        u_rom_b0_16.mem[11] = 64'h0000000000000000;
        u_rom_b0_16.mem[12] = 64'h0000000000000000;
        u_rom_b0_16.mem[13] = 64'h0000000000000000;
        u_rom_b0_16.mem[14] = 64'h0000000000000000;
        u_rom_b0_16.mem[15] = 64'h0000000000000000;
        u_rom_b0_16.mem[16] = 64'h0000000000000000;
        u_rom_b0_16.mem[17] = 64'h0000000000000000;
        u_rom_b0_16.mem[18] = 64'h0000000000000000;
        u_rom_b0_16.mem[19] = 64'h0000000000000000;
        u_rom_b0_16.mem[20] = 64'h0000000000000000;
        u_rom_b0_16.mem[21] = 64'h0000000000000000;
        u_rom_b0_16.mem[22] = 64'h0000000000000000;
        u_rom_b0_16.mem[23] = 64'h0000000000000000;
        u_rom_b0_16.mem[24] = 64'h0000000000000000;
        u_rom_b0_16.mem[25] = 64'h0000000000000000;
        u_rom_b0_16.mem[26] = 64'h0000000000000000;
        u_rom_b0_16.mem[27] = 64'h0000000000000000;
        u_rom_b0_16.mem[28] = 64'h0000000000000000;
        u_rom_b0_16.mem[29] = 64'h0000000000000000;
        u_rom_b0_16.mem[30] = 64'h0000000000000000;
        u_rom_b0_16.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 17  (sel == 5'b10001)
    wire oe_b0_17 = (sel == 5'd17);
    rom64b32w$ u_rom_b0_17 (
        .A    (addr),
        .OE   (oe_b0_17),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_17.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_17.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_17.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_17.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_17.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_17.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_17.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_17.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_17.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_17.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_17.mem[10] = 64'h0000000000000000;
        u_rom_b0_17.mem[11] = 64'h0000000000000000;
        u_rom_b0_17.mem[12] = 64'h0000000000000000;
        u_rom_b0_17.mem[13] = 64'h0000000000000000;
        u_rom_b0_17.mem[14] = 64'h0000000000000000;
        u_rom_b0_17.mem[15] = 64'h0000000000000000;
        u_rom_b0_17.mem[16] = 64'h0000000000000000;
        u_rom_b0_17.mem[17] = 64'h0000000000000000;
        u_rom_b0_17.mem[18] = 64'h0000000000000000;
        u_rom_b0_17.mem[19] = 64'h0000000000000000;
        u_rom_b0_17.mem[20] = 64'h0000000000000000;
        u_rom_b0_17.mem[21] = 64'h0000000000000000;
        u_rom_b0_17.mem[22] = 64'h0000000000000000;
        u_rom_b0_17.mem[23] = 64'h0000000000000000;
        u_rom_b0_17.mem[24] = 64'h0000000000000000;
        u_rom_b0_17.mem[25] = 64'h0000000000000000;
        u_rom_b0_17.mem[26] = 64'h0000000000000000;
        u_rom_b0_17.mem[27] = 64'h0000000000000000;
        u_rom_b0_17.mem[28] = 64'h0000000000000000;
        u_rom_b0_17.mem[29] = 64'h0000000000000000;
        u_rom_b0_17.mem[30] = 64'h0000000000000000;
        u_rom_b0_17.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 18  (sel == 5'b10010)
    wire oe_b0_18 = (sel == 5'd18);
    rom64b32w$ u_rom_b0_18 (
        .A    (addr),
        .OE   (oe_b0_18),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_18.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_18.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_18.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_18.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_18.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_18.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_18.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_18.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_18.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_18.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_18.mem[10] = 64'h0000000000000000;
        u_rom_b0_18.mem[11] = 64'h0000000000000000;
        u_rom_b0_18.mem[12] = 64'h0000000000000000;
        u_rom_b0_18.mem[13] = 64'h0000000000000000;
        u_rom_b0_18.mem[14] = 64'h0000000000000000;
        u_rom_b0_18.mem[15] = 64'h0000000000000000;
        u_rom_b0_18.mem[16] = 64'h0000000000000000;
        u_rom_b0_18.mem[17] = 64'h0000000000000000;
        u_rom_b0_18.mem[18] = 64'h0000000000000000;
        u_rom_b0_18.mem[19] = 64'h0000000000000000;
        u_rom_b0_18.mem[20] = 64'h0000000000000000;
        u_rom_b0_18.mem[21] = 64'h0000000000000000;
        u_rom_b0_18.mem[22] = 64'h0000000000000000;
        u_rom_b0_18.mem[23] = 64'h0000000000000000;
        u_rom_b0_18.mem[24] = 64'h0000000000000000;
        u_rom_b0_18.mem[25] = 64'h0000000000000000;
        u_rom_b0_18.mem[26] = 64'h0000000000000000;
        u_rom_b0_18.mem[27] = 64'h0000000000000000;
        u_rom_b0_18.mem[28] = 64'h0000000000000000;
        u_rom_b0_18.mem[29] = 64'h0000000000000000;
        u_rom_b0_18.mem[30] = 64'h0000000000000000;
        u_rom_b0_18.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 19  (sel == 5'b10011)
    wire oe_b0_19 = (sel == 5'd19);
    rom64b32w$ u_rom_b0_19 (
        .A    (addr),
        .OE   (oe_b0_19),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_19.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_19.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_19.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_19.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_19.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_19.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_19.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_19.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_19.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_19.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_19.mem[10] = 64'h0000000000000000;
        u_rom_b0_19.mem[11] = 64'h0000000000000000;
        u_rom_b0_19.mem[12] = 64'h0000000000000000;
        u_rom_b0_19.mem[13] = 64'h0000000000000000;
        u_rom_b0_19.mem[14] = 64'h0000000000000000;
        u_rom_b0_19.mem[15] = 64'h0000000000000000;
        u_rom_b0_19.mem[16] = 64'h0000000000000000;
        u_rom_b0_19.mem[17] = 64'h0000000000000000;
        u_rom_b0_19.mem[18] = 64'h0000000000000000;
        u_rom_b0_19.mem[19] = 64'h0000000000000000;
        u_rom_b0_19.mem[20] = 64'h0000000000000000;
        u_rom_b0_19.mem[21] = 64'h0000000000000000;
        u_rom_b0_19.mem[22] = 64'h0000000000000000;
        u_rom_b0_19.mem[23] = 64'h0000000000000000;
        u_rom_b0_19.mem[24] = 64'h0000000000000000;
        u_rom_b0_19.mem[25] = 64'h0000000000000000;
        u_rom_b0_19.mem[26] = 64'h0000000000000000;
        u_rom_b0_19.mem[27] = 64'h0000000000000000;
        u_rom_b0_19.mem[28] = 64'h0000000000000000;
        u_rom_b0_19.mem[29] = 64'h0000000000000000;
        u_rom_b0_19.mem[30] = 64'h0000000000000000;
        u_rom_b0_19.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 20  (sel == 5'b10100)
    wire oe_b0_20 = (sel == 5'd20);
    rom64b32w$ u_rom_b0_20 (
        .A    (addr),
        .OE   (oe_b0_20),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_20.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_20.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_20.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_20.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_20.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_20.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_20.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_20.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_20.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_20.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_20.mem[10] = 64'h0000000000000000;
        u_rom_b0_20.mem[11] = 64'h0000000000000000;
        u_rom_b0_20.mem[12] = 64'h0000000000000000;
        u_rom_b0_20.mem[13] = 64'h0000000000000000;
        u_rom_b0_20.mem[14] = 64'h0000000000000000;
        u_rom_b0_20.mem[15] = 64'h0000000000000000;
        u_rom_b0_20.mem[16] = 64'h0000000000000000;
        u_rom_b0_20.mem[17] = 64'h0000000000000000;
        u_rom_b0_20.mem[18] = 64'h0000000000000000;
        u_rom_b0_20.mem[19] = 64'h0000000000000000;
        u_rom_b0_20.mem[20] = 64'h0000000000000000;
        u_rom_b0_20.mem[21] = 64'h0000000000000000;
        u_rom_b0_20.mem[22] = 64'h0000000000000000;
        u_rom_b0_20.mem[23] = 64'h0000000000000000;
        u_rom_b0_20.mem[24] = 64'h0000000000000000;
        u_rom_b0_20.mem[25] = 64'h0000000000000000;
        u_rom_b0_20.mem[26] = 64'h0000000000000000;
        u_rom_b0_20.mem[27] = 64'h0000000000000000;
        u_rom_b0_20.mem[28] = 64'h0000000000000000;
        u_rom_b0_20.mem[29] = 64'h0000000000000000;
        u_rom_b0_20.mem[30] = 64'h0000000000000000;
        u_rom_b0_20.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 21  (sel == 5'b10101)
    wire oe_b0_21 = (sel == 5'd21);
    rom64b32w$ u_rom_b0_21 (
        .A    (addr),
        .OE   (oe_b0_21),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_21.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_21.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_21.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_21.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_21.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_21.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_21.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_21.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_21.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_21.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_21.mem[10] = 64'h0000000000000000;
        u_rom_b0_21.mem[11] = 64'h0000000000000000;
        u_rom_b0_21.mem[12] = 64'h0000000000000000;
        u_rom_b0_21.mem[13] = 64'h0000000000000000;
        u_rom_b0_21.mem[14] = 64'h0000000000000000;
        u_rom_b0_21.mem[15] = 64'h0000000000000000;
        u_rom_b0_21.mem[16] = 64'h0000000000000000;
        u_rom_b0_21.mem[17] = 64'h0000000000000000;
        u_rom_b0_21.mem[18] = 64'h0000000000000000;
        u_rom_b0_21.mem[19] = 64'h0000000000000000;
        u_rom_b0_21.mem[20] = 64'h0000000000000000;
        u_rom_b0_21.mem[21] = 64'h0000000000000000;
        u_rom_b0_21.mem[22] = 64'h0000000000000000;
        u_rom_b0_21.mem[23] = 64'h0000000000000000;
        u_rom_b0_21.mem[24] = 64'h0000000000000000;
        u_rom_b0_21.mem[25] = 64'h0000000000000000;
        u_rom_b0_21.mem[26] = 64'h0000000000000000;
        u_rom_b0_21.mem[27] = 64'h0000000000000000;
        u_rom_b0_21.mem[28] = 64'h0000000000000000;
        u_rom_b0_21.mem[29] = 64'h0000000000000000;
        u_rom_b0_21.mem[30] = 64'h0000000000000000;
        u_rom_b0_21.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 22  (sel == 5'b10110)
    wire oe_b0_22 = (sel == 5'd22);
    rom64b32w$ u_rom_b0_22 (
        .A    (addr),
        .OE   (oe_b0_22),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_22.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_22.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_22.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_22.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_22.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_22.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_22.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_22.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_22.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_22.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_22.mem[10] = 64'h0000000000000000;
        u_rom_b0_22.mem[11] = 64'h0000000000000000;
        u_rom_b0_22.mem[12] = 64'h0000000000000000;
        u_rom_b0_22.mem[13] = 64'h0000000000000000;
        u_rom_b0_22.mem[14] = 64'h0000000000000000;
        u_rom_b0_22.mem[15] = 64'h0000000000000000;
        u_rom_b0_22.mem[16] = 64'h0000000000000000;
        u_rom_b0_22.mem[17] = 64'h0000000000000000;
        u_rom_b0_22.mem[18] = 64'h0000000000000000;
        u_rom_b0_22.mem[19] = 64'h0000000000000000;
        u_rom_b0_22.mem[20] = 64'h0000000000000000;
        u_rom_b0_22.mem[21] = 64'h0000000000000000;
        u_rom_b0_22.mem[22] = 64'h0000000000000000;
        u_rom_b0_22.mem[23] = 64'h0000000000000000;
        u_rom_b0_22.mem[24] = 64'h0000000000000000;
        u_rom_b0_22.mem[25] = 64'h0000000000000000;
        u_rom_b0_22.mem[26] = 64'h0000000000000000;
        u_rom_b0_22.mem[27] = 64'h0000000000000000;
        u_rom_b0_22.mem[28] = 64'h0000000000000000;
        u_rom_b0_22.mem[29] = 64'h0000000000000000;
        u_rom_b0_22.mem[30] = 64'h0000000000000000;
        u_rom_b0_22.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 23  (sel == 5'b10111)
    wire oe_b0_23 = (sel == 5'd23);
    rom64b32w$ u_rom_b0_23 (
        .A    (addr),
        .OE   (oe_b0_23),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_23.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_23.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_23.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_23.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_23.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_23.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_23.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_23.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_23.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_23.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_23.mem[10] = 64'h0000000000000000;
        u_rom_b0_23.mem[11] = 64'h0000000000000000;
        u_rom_b0_23.mem[12] = 64'h0000000000000000;
        u_rom_b0_23.mem[13] = 64'h0000000000000000;
        u_rom_b0_23.mem[14] = 64'h0000000000000000;
        u_rom_b0_23.mem[15] = 64'h0000000000000000;
        u_rom_b0_23.mem[16] = 64'h0000000000000000;
        u_rom_b0_23.mem[17] = 64'h0000000000000000;
        u_rom_b0_23.mem[18] = 64'h0000000000000000;
        u_rom_b0_23.mem[19] = 64'h0000000000000000;
        u_rom_b0_23.mem[20] = 64'h0000000000000000;
        u_rom_b0_23.mem[21] = 64'h0000000000000000;
        u_rom_b0_23.mem[22] = 64'h0000000000000000;
        u_rom_b0_23.mem[23] = 64'h0000000000000000;
        u_rom_b0_23.mem[24] = 64'h0000000000000000;
        u_rom_b0_23.mem[25] = 64'h0000000000000000;
        u_rom_b0_23.mem[26] = 64'h0000000000000000;
        u_rom_b0_23.mem[27] = 64'h0000000000000000;
        u_rom_b0_23.mem[28] = 64'h0000000000000000;
        u_rom_b0_23.mem[29] = 64'h0000000000000000;
        u_rom_b0_23.mem[30] = 64'h0000000000000000;
        u_rom_b0_23.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 24  (sel == 5'b11000)
    wire oe_b0_24 = (sel == 5'd24);
    rom64b32w$ u_rom_b0_24 (
        .A    (addr),
        .OE   (oe_b0_24),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_24.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_24.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_24.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_24.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_24.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_24.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_24.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_24.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_24.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_24.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_24.mem[10] = 64'h0000000000000000;
        u_rom_b0_24.mem[11] = 64'h0000000000000000;
        u_rom_b0_24.mem[12] = 64'h0000000000000000;
        u_rom_b0_24.mem[13] = 64'h0000000000000000;
        u_rom_b0_24.mem[14] = 64'h0000000000000000;
        u_rom_b0_24.mem[15] = 64'h0000000000000000;
        u_rom_b0_24.mem[16] = 64'h0000000000000000;
        u_rom_b0_24.mem[17] = 64'h0000000000000000;
        u_rom_b0_24.mem[18] = 64'h0000000000000000;
        u_rom_b0_24.mem[19] = 64'h0000000000000000;
        u_rom_b0_24.mem[20] = 64'h0000000000000000;
        u_rom_b0_24.mem[21] = 64'h0000000000000000;
        u_rom_b0_24.mem[22] = 64'h0000000000000000;
        u_rom_b0_24.mem[23] = 64'h0000000000000000;
        u_rom_b0_24.mem[24] = 64'h0000000000000000;
        u_rom_b0_24.mem[25] = 64'h0000000000000000;
        u_rom_b0_24.mem[26] = 64'h0000000000000000;
        u_rom_b0_24.mem[27] = 64'h0000000000000000;
        u_rom_b0_24.mem[28] = 64'h0000000000000000;
        u_rom_b0_24.mem[29] = 64'h0000000000000000;
        u_rom_b0_24.mem[30] = 64'h0000000000000000;
        u_rom_b0_24.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 25  (sel == 5'b11001)
    wire oe_b0_25 = (sel == 5'd25);
    rom64b32w$ u_rom_b0_25 (
        .A    (addr),
        .OE   (oe_b0_25),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_25.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_25.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_25.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_25.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_25.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_25.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_25.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_25.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_25.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_25.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_25.mem[10] = 64'h0000000000000000;
        u_rom_b0_25.mem[11] = 64'h0000000000000000;
        u_rom_b0_25.mem[12] = 64'h0000000000000000;
        u_rom_b0_25.mem[13] = 64'h0000000000000000;
        u_rom_b0_25.mem[14] = 64'h0000000000000000;
        u_rom_b0_25.mem[15] = 64'h0000000000000000;
        u_rom_b0_25.mem[16] = 64'h0000000000000000;
        u_rom_b0_25.mem[17] = 64'h0000000000000000;
        u_rom_b0_25.mem[18] = 64'h0000000000000000;
        u_rom_b0_25.mem[19] = 64'h0000000000000000;
        u_rom_b0_25.mem[20] = 64'h0000000000000000;
        u_rom_b0_25.mem[21] = 64'h0000000000000000;
        u_rom_b0_25.mem[22] = 64'h0000000000000000;
        u_rom_b0_25.mem[23] = 64'h0000000000000000;
        u_rom_b0_25.mem[24] = 64'h0000000000000000;
        u_rom_b0_25.mem[25] = 64'h0000000000000000;
        u_rom_b0_25.mem[26] = 64'h0000000000000000;
        u_rom_b0_25.mem[27] = 64'h0000000000000000;
        u_rom_b0_25.mem[28] = 64'h0000000000000000;
        u_rom_b0_25.mem[29] = 64'h0000000000000000;
        u_rom_b0_25.mem[30] = 64'h0000000000000000;
        u_rom_b0_25.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 26  (sel == 5'b11010)
    wire oe_b0_26 = (sel == 5'd26);
    rom64b32w$ u_rom_b0_26 (
        .A    (addr),
        .OE   (oe_b0_26),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_26.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_26.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_26.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_26.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_26.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_26.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_26.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_26.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_26.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_26.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_26.mem[10] = 64'h0000000000000000;
        u_rom_b0_26.mem[11] = 64'h0000000000000000;
        u_rom_b0_26.mem[12] = 64'h0000000000000000;
        u_rom_b0_26.mem[13] = 64'h0000000000000000;
        u_rom_b0_26.mem[14] = 64'h0000000000000000;
        u_rom_b0_26.mem[15] = 64'h0000000000000000;
        u_rom_b0_26.mem[16] = 64'h0000000000000000;
        u_rom_b0_26.mem[17] = 64'h0000000000000000;
        u_rom_b0_26.mem[18] = 64'h0000000000000000;
        u_rom_b0_26.mem[19] = 64'h0000000000000000;
        u_rom_b0_26.mem[20] = 64'h0000000000000000;
        u_rom_b0_26.mem[21] = 64'h0000000000000000;
        u_rom_b0_26.mem[22] = 64'h0000000000000000;
        u_rom_b0_26.mem[23] = 64'h0000000000000000;
        u_rom_b0_26.mem[24] = 64'h0000000000000000;
        u_rom_b0_26.mem[25] = 64'h0000000000000000;
        u_rom_b0_26.mem[26] = 64'h0000000000000000;
        u_rom_b0_26.mem[27] = 64'h0000000000000000;
        u_rom_b0_26.mem[28] = 64'h0000000000000000;
        u_rom_b0_26.mem[29] = 64'h0000000000000000;
        u_rom_b0_26.mem[30] = 64'h0000000000000000;
        u_rom_b0_26.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 27  (sel == 5'b11011)
    wire oe_b0_27 = (sel == 5'd27);
    rom64b32w$ u_rom_b0_27 (
        .A    (addr),
        .OE   (oe_b0_27),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_27.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_27.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_27.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_27.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_27.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_27.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_27.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_27.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_27.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_27.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_27.mem[10] = 64'h0000000000000000;
        u_rom_b0_27.mem[11] = 64'h0000000000000000;
        u_rom_b0_27.mem[12] = 64'h0000000000000000;
        u_rom_b0_27.mem[13] = 64'h0000000000000000;
        u_rom_b0_27.mem[14] = 64'h0000000000000000;
        u_rom_b0_27.mem[15] = 64'h0000000000000000;
        u_rom_b0_27.mem[16] = 64'h0000000000000000;
        u_rom_b0_27.mem[17] = 64'h0000000000000000;
        u_rom_b0_27.mem[18] = 64'h0000000000000000;
        u_rom_b0_27.mem[19] = 64'h0000000000000000;
        u_rom_b0_27.mem[20] = 64'h0000000000000000;
        u_rom_b0_27.mem[21] = 64'h0000000000000000;
        u_rom_b0_27.mem[22] = 64'h0000000000000000;
        u_rom_b0_27.mem[23] = 64'h0000000000000000;
        u_rom_b0_27.mem[24] = 64'h0000000000000000;
        u_rom_b0_27.mem[25] = 64'h0000000000000000;
        u_rom_b0_27.mem[26] = 64'h0000000000000000;
        u_rom_b0_27.mem[27] = 64'h0000000000000000;
        u_rom_b0_27.mem[28] = 64'h0000000000000000;
        u_rom_b0_27.mem[29] = 64'h0000000000000000;
        u_rom_b0_27.mem[30] = 64'h0000000000000000;
        u_rom_b0_27.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 28  (sel == 5'b11100)
    wire oe_b0_28 = (sel == 5'd28);
    rom64b32w$ u_rom_b0_28 (
        .A    (addr),
        .OE   (oe_b0_28),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_28.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_28.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_28.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_28.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_28.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_28.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_28.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_28.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_28.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_28.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_28.mem[10] = 64'h0000000000000000;
        u_rom_b0_28.mem[11] = 64'h0000000000000000;
        u_rom_b0_28.mem[12] = 64'h0000000000000000;
        u_rom_b0_28.mem[13] = 64'h0000000000000000;
        u_rom_b0_28.mem[14] = 64'h0000000000000000;
        u_rom_b0_28.mem[15] = 64'h0000000000000000;
        u_rom_b0_28.mem[16] = 64'h0000000000000000;
        u_rom_b0_28.mem[17] = 64'h0000000000000000;
        u_rom_b0_28.mem[18] = 64'h0000000000000000;
        u_rom_b0_28.mem[19] = 64'h0000000000000000;
        u_rom_b0_28.mem[20] = 64'h0000000000000000;
        u_rom_b0_28.mem[21] = 64'h0000000000000000;
        u_rom_b0_28.mem[22] = 64'h0000000000000000;
        u_rom_b0_28.mem[23] = 64'h0000000000000000;
        u_rom_b0_28.mem[24] = 64'h0000000000000000;
        u_rom_b0_28.mem[25] = 64'h0000000000000000;
        u_rom_b0_28.mem[26] = 64'h0000000000000000;
        u_rom_b0_28.mem[27] = 64'h0000000000000000;
        u_rom_b0_28.mem[28] = 64'h0000000000000000;
        u_rom_b0_28.mem[29] = 64'h0000000000000000;
        u_rom_b0_28.mem[30] = 64'h0000000000000000;
        u_rom_b0_28.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 29  (sel == 5'b11101)
    wire oe_b0_29 = (sel == 5'd29);
    rom64b32w$ u_rom_b0_29 (
        .A    (addr),
        .OE   (oe_b0_29),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_29.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_29.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_29.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_29.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_29.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_29.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_29.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_29.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_29.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_29.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_29.mem[10] = 64'h0000000000000000;
        u_rom_b0_29.mem[11] = 64'h0000000000000000;
        u_rom_b0_29.mem[12] = 64'h0000000000000000;
        u_rom_b0_29.mem[13] = 64'h0000000000000000;
        u_rom_b0_29.mem[14] = 64'h0000000000000000;
        u_rom_b0_29.mem[15] = 64'h0000000000000000;
        u_rom_b0_29.mem[16] = 64'h0000000000000000;
        u_rom_b0_29.mem[17] = 64'h0000000000000000;
        u_rom_b0_29.mem[18] = 64'h0000000000000000;
        u_rom_b0_29.mem[19] = 64'h0000000000000000;
        u_rom_b0_29.mem[20] = 64'h0000000000000000;
        u_rom_b0_29.mem[21] = 64'h0000000000000000;
        u_rom_b0_29.mem[22] = 64'h0000000000000000;
        u_rom_b0_29.mem[23] = 64'h0000000000000000;
        u_rom_b0_29.mem[24] = 64'h0000000000000000;
        u_rom_b0_29.mem[25] = 64'h0000000000000000;
        u_rom_b0_29.mem[26] = 64'h0000000000000000;
        u_rom_b0_29.mem[27] = 64'h0000000000000000;
        u_rom_b0_29.mem[28] = 64'h0000000000000000;
        u_rom_b0_29.mem[29] = 64'h0000000000000000;
        u_rom_b0_29.mem[30] = 64'h0000000000000000;
        u_rom_b0_29.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 30  (sel == 5'b11110)
    wire oe_b0_30 = (sel == 5'd30);
    rom64b32w$ u_rom_b0_30 (
        .A    (addr),
        .OE   (oe_b0_30),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_30.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_30.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_30.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_30.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_30.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_30.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_30.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_30.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_30.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_30.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_30.mem[10] = 64'h0000000000000000;
        u_rom_b0_30.mem[11] = 64'h0000000000000000;
        u_rom_b0_30.mem[12] = 64'h0000000000000000;
        u_rom_b0_30.mem[13] = 64'h0000000000000000;
        u_rom_b0_30.mem[14] = 64'h0000000000000000;
        u_rom_b0_30.mem[15] = 64'h0000000000000000;
        u_rom_b0_30.mem[16] = 64'h0000000000000000;
        u_rom_b0_30.mem[17] = 64'h0000000000000000;
        u_rom_b0_30.mem[18] = 64'h0000000000000000;
        u_rom_b0_30.mem[19] = 64'h0000000000000000;
        u_rom_b0_30.mem[20] = 64'h0000000000000000;
        u_rom_b0_30.mem[21] = 64'h0000000000000000;
        u_rom_b0_30.mem[22] = 64'h0000000000000000;
        u_rom_b0_30.mem[23] = 64'h0000000000000000;
        u_rom_b0_30.mem[24] = 64'h0000000000000000;
        u_rom_b0_30.mem[25] = 64'h0000000000000000;
        u_rom_b0_30.mem[26] = 64'h0000000000000000;
        u_rom_b0_30.mem[27] = 64'h0000000000000000;
        u_rom_b0_30.mem[28] = 64'h0000000000000000;
        u_rom_b0_30.mem[29] = 64'h0000000000000000;
        u_rom_b0_30.mem[30] = 64'h0000000000000000;
        u_rom_b0_30.mem[31] = 64'h0000000000000000;
    end

    // Bank 0, ROM 31  (sel == 5'b11111)
    wire oe_b0_31 = (sel == 5'd31);
    rom64b32w$ u_rom_b0_31 (
        .A    (addr),
        .OE   (oe_b0_31),
        .DOUT (dout_bus_0)
    );
    initial begin
        u_rom_b0_31.mem[ 0] = 64'h0000000000000000;
        u_rom_b0_31.mem[ 1] = 64'h0000000000000000;
        u_rom_b0_31.mem[ 2] = 64'h0000000000000000;
        u_rom_b0_31.mem[ 3] = 64'h0000000000000000;
        u_rom_b0_31.mem[ 4] = 64'h0000000000000000;
        u_rom_b0_31.mem[ 5] = 64'h0000000000000000;
        u_rom_b0_31.mem[ 6] = 64'h0000000000000000;
        u_rom_b0_31.mem[ 7] = 64'h0000000000000000;
        u_rom_b0_31.mem[ 8] = 64'h0000000000000000;
        u_rom_b0_31.mem[ 9] = 64'h0000000000000000;
        u_rom_b0_31.mem[10] = 64'h0000000000000000;
        u_rom_b0_31.mem[11] = 64'h0000000000000000;
        u_rom_b0_31.mem[12] = 64'h0000000000000000;
        u_rom_b0_31.mem[13] = 64'h0000000000000000;
        u_rom_b0_31.mem[14] = 64'h0000000000000000;
        u_rom_b0_31.mem[15] = 64'h0000000000000000;
        u_rom_b0_31.mem[16] = 64'h0000000000000000;
        u_rom_b0_31.mem[17] = 64'h0000000000000000;
        u_rom_b0_31.mem[18] = 64'h0000000000000000;
        u_rom_b0_31.mem[19] = 64'h0000000000000000;
        u_rom_b0_31.mem[20] = 64'h0000000000000000;
        u_rom_b0_31.mem[21] = 64'h0000000000000000;
        u_rom_b0_31.mem[22] = 64'h0000000000000000;
        u_rom_b0_31.mem[23] = 64'h0000000000000000;
        u_rom_b0_31.mem[24] = 64'h0000000000000000;
        u_rom_b0_31.mem[25] = 64'h0000000000000000;
        u_rom_b0_31.mem[26] = 64'h0000000000000000;
        u_rom_b0_31.mem[27] = 64'h0000000000000000;
        u_rom_b0_31.mem[28] = 64'h0000000000000000;
        u_rom_b0_31.mem[29] = 64'h0000000000000000;
        u_rom_b0_31.mem[30] = 64'h0000000000000000;
        u_rom_b0_31.mem[31] = 64'h0000000000000000;
    end

endmodule
