ICACHE_PATH_INTERNAL = $(ROOT)/rtl/ICache/

ICACHE_GEN_SRC_FILES = \


ICACHE_SRC_FILES = \
					$(ICACHE_GEN_SRC_FILES)	\
					$(ICACHE_PATH_INTERNAL)/ICache.sv	\

ICACHE_PKGS = \
			  $(ICACHE_PATH_INTERNAL)/pkg/ICache_pkg.sv
