DCACHE_PATH_INTERNAL = $(ROOT)/rtl/DCache/

DCACHE_GEN_SRC_FILES = \


DCACHE_SRC_FILES = \
					$(DCACHE_GEN_SRC_FILES)	\
					$(DCACHE_PATH_INTERNAL)/DCache.sv	\

DCACHE_PKGS = \
			  $(DCACHE_PATH_INTERNAL)/pkg/DCache_pkg.sv
