`ifndef COMMONDEFINES_VH
`define COMMONDEFINES_VH

`define CACHE_LINES_SIZE_B (16)
`define CACHE_LINES_SIZE_BITS (`CACHE_LINES_SIZE_B * 8)
`define ADDRESS_BITS (32)
`define PAGE_SIZE (4096)
`define PHY_MEM_SIZE (1 << 15)
`define DATA_BUS_WIDTH_BITS (32)
`define ADDRESS_BUS_WIDTH_BITS (32)
`define NUM_WB_ST_QS (4)
`define ST_Q_DEPTH (4)
`define NUM_IDM_SLOTS (4)
`define NUM_SBS (22)

`endif
