#!/usr/bin/env python3
"""
genInitRitual.py
----------------
Stage 3 of the memGen pipeline.

Reads the JSON config and generates:
  <readmemFilePath> – the tb_memGen_InitRitual module with fully unrolled
                      $readmemh calls (no loop variables in hierarchical
                      paths so VCS can elaborate statically)

JSON config keys consumed here:
  output_LoadableHex_Path : base path used in $readmemh filename strings
  readmemFilePath         : output path for the ritual .sv file
  memCellPath             : hierarchical path template, use <bankNum> and
                            <cellNum> as placeholders
  startUpDelay            : number of clocks to wait before loading
  pkg_Name                : name of the package to import (user-provided)
  num_banks               : number of banks (default 64)
  cells_per_bank          : cells per bank (default 4)
"""

import json, os, argparse

DEFAULT_NUM_BANKS = 64
DEFAULT_CELLS     = 4

def load_config(path: str) -> dict:
    with open(path) as f:
        return json.load(f)

def make_dir(p: str):
    d = os.path.dirname(p)
    if d:
        os.makedirs(d, exist_ok=True)

def gen_ritual(cfg: dict):
    num_banks   = int(cfg.get('num_banks',      DEFAULT_NUM_BANKS))
    cells       = int(cfg.get('cells_per_bank', DEFAULT_CELLS))
    hex_dir     = cfg['output_LoadableHex_Path'].rstrip('/')
    cell_path_t = cfg['memCellPath']
    delay       = cfg.get('startUpDelay', '3')
    ritual_path = cfg['readmemFilePath']
    pkg_name    = os.path.splitext(os.path.basename(cfg['pkg_Name']))[0]

    lines = []
    lines.append(f"// Auto-generated by genInitRitual.py")
    lines.append(f"// Fully unrolled $readmemh calls — no loop variables in")
    lines.append(f"// hierarchical paths so VCS can elaborate statically.")
    lines.append(f"")
    lines.append(f"import {pkg_name}::*;")
    lines.append(f"")
    lines.append(f"module tb_memGen_InitRitual ();")
    lines.append(f"")
    lines.append(f"    initial begin")
    lines.append(f"        DelayCLKs({delay});")

    for b in range(num_banks):
        for c in range(cells):
            fname    = f"{hex_dir}/mem_{b}_{c}.hex"
            mem_path = (cell_path_t
                        .replace('<bankNum>', str(b))
                        .replace('<cellNum>', str(c)))
            lines.append(f'        $readmemh("{fname}", {mem_path});')

    lines.append(f"    end")
    lines.append(f"")
    lines.append(f"endmodule")
    lines.append(f"")

    make_dir(ritual_path)
    with open(ritual_path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"[genInitRitual] Wrote ritual → {ritual_path}  "
          f"({num_banks * cells} readmemh calls)")

def main():
    ap = argparse.ArgumentParser(
        description="Stage 3: generate unrolled $readmemh ritual SV file")
    ap.add_argument('config', help='Path to JSON config file')
    args = ap.parse_args()
    cfg = load_config(args.config)
    gen_ritual(cfg)
    print("[genInitRitual] Done.")

if __name__ == '__main__':
    main()
